### ISSUE TITLE
Explorer doesn't show the balance change in the transaction "State" or "Internal txns" sections

### ISSUE THREAD

**Issue by R-Santev** [blockscout/blockscout#9746] opened 2024-03-28 14:26 UTC
### Description

The explorer shows the balance change in the "Coin balance history" section of a contract, but it doesn't show the balance change in the transaction "State" or "Internal txns" sections.

Node tracing is enabled.

Here is a tx where this occurs: https://hydragon.hydrachain.org/tx/0xcc3c912482381da2216fceb69e432acedc9b4a934fb813c368b7fef70e7186b7?tab=index

Here we can see the undelegated amount:
<img width="1220" alt="image" src="https://github.com/blockscout/blockscout/assets/77731162/399634eb-71ec-4415-8fb9-3c0d995e08af">
Here is the actual withdrawal amount:
<img width="1199" alt="image" src="https://github.com/blockscout/blockscout/assets/77731162/b9277ead-78b0-412d-9d63-cdce4bd968de">

The difference between the two amounts must be burned and we can see that in the "Coin balance history" of the contract:
https://hydragon.hydrachain.org/address/0x0000000000000000000000000000000000000101?tab=coin_balance_history
<img width="1239" alt="image" src="https://github.com/blockscout/blockscout/assets/77731162/069a9835-3350-47e1-a462-a85f568a639e">

Why the burned amount is not shown in the "State" tab of the transaction?

Thanks in advance!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygonEdge

### Type of the chain

L1

### Backend version

v5.4.0

### Frontend version

v1.24.1

### Elixir & Erlang/OTP versions

unknown

### Operating system

Linux

**Comment by GimluCom** [comment] 2024-04-01 23:53
It looks like you are not indexing [internal transactions](https://hydragon.hydrachain.org/tx/0xcc3c912482381da2216fceb69e432acedc9b4a934fb813c368b7fef70e7186b7?tab=internal). Please check that you have not disabled it in your ENVs and that there are no errors appearing in your logs.

**Comment by R-Santev** [comment] 2024-04-02 07:21
Thanks for answering, @GimluCom !

Could you give me some more information:
- Which env variable to check and is it in the backend container or anyone else?
- Where I can find the logs for the specific service responsible for the internal transactions indexing?

**Comment by GimluCom** [comment] 2024-04-08 15:44
[`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=false`](https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management)

`docker compose logs backend` or in the `services/logs/` file. Check for any errors in the backend.

**Comment by R-Santev** [comment] 2024-04-10 11:26
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER is `false`
INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE is `polygon_edge`

Here is the error that the backend returns:

```
2024-04-10T11:12:13.954Z failed to fetch internal transactions for blocks: ** (MatchError) no match of right hand side value: {"0x2d5d7eef5827eb892", ["0xfd242c14"]}
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:292: EthereumJSONRPC.Geth.PolygonTracer.call_op/3
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:52: EthereumJSONRPC.Geth.PolygonTracer.replay/3
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:239: anonymous fn/5 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:233: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (indexer 6.4.0) lib/indexer/fetcher/internal_transaction.ex:225: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
 | severity=error metadata={"count":3,"error_count":3,"fetcher":"internal_transaction"}
2024-04-10T11:12:15.747Z Start sanitizing of empty blocks. Batch size is 20 | severity=info metadata={"fetcher":"empty_blocks_to_refetch"}
2024-04-10T11:12:16.172Z failed to fetch internal transactions for blocks: ** (MatchError) no match of right hand side value: {"0x2d5d7eef5827eb892", ["0xfd242c14"]}
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:292: EthereumJSONRPC.Geth.PolygonTracer.call_op/3
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:52: EthereumJSONRPC.Geth.PolygonTracer.replay/3
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:239: anonymous fn/5 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:233: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (indexer 6.4.0) lib/indexer/fetcher/internal_transaction.ex:225: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
 | severity=error metadata={"count":3,"error_count":3,"fetcher":"internal_transaction"}
```

@GimluCom Could you give more information based on the logs?

**Comment by GimluCom** [comment] 2024-04-16 01:53
Set `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=1`

Is your RPC node an unmodified Polygon Edge RPC node?

Could you share the output of
```sh
curl http://127.0.0.1:8545 -H "Content-Type: application/json" -d '{"method":"debug_traceTransaction","params":["0xcc3c912482381da2216fceb69e432acedc9b4a934fb813c368b7fef70e7186b7",{"enableMemory":true,"disableStack":false,"disableStorage":true,"enableReturnData":false}],"id":1,"jsonrpc":"2.0"}' -o out.json
```

**Comment by R-Santev** [comment] 2024-04-17 10:11
Here is the output:
[out.json](https://github.com/blockscout/blockscout/files/15009270/out.json)

Here are the error logs I can see:
```
2024-04-17T10:07:26.326Z failed to fetch internal transactions for blocks: ** (FunctionClauseError) no function clause matching in anonymous fn/1 in EthereumJSONRPC.Geth.fetch_missing_data/2
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:277: anonymous fn(%{error: %{code: -32602, message: "Invalid Params"}, id: 1, jsonrpc: "2.0"}) in EthereumJSONRPC.Geth.fetch_missing_data/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.5) lib/enum.ex:1552: Enum.into/3
    (ethereum_jsonrpc 6.4.0) lib/ethereum_jsonrpc/geth.ex:277: EthereumJSONRPC.Geth.fetch_missing_data/2
    (indexer 6.4.0) lib/indexer/fetcher/internal_transaction.ex:225: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (indexer 6.4.0) lib/indexer/fetcher/internal_transaction.ex:155: Indexer.Fetcher.InternalTransaction.fetch_internal_transactions/3
    (indexer 6.4.0) lib/indexer/fetcher/internal_transaction.ex:114: Indexer.Fetcher.InternalTransaction.run/2
 | severity=error metadata={"count":1,"error_count":1,"fetcher":"internal_transaction"}
```

```
2024-04-17T10:06:49.088Z failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: :enomem | severity=error metadata={"count":1,"error_count":1,"fetcher":"internal_transaction"}
```

And there are also some logs with the match error I shared in the previous comment.
@GimluCom

**Comment by phpmac** [comment] 2024-05-08 11:05
I also encountered the same error

**Comment by R-Santev** [comment] 2024-05-08 12:39
> I also encountered the same error
Which version of polygon-edge do you use? @phpmac

**Comment by phpmac** [comment] 2024-05-08 16:05
> > I also encountered the same errorI also encountered the same error
>
> Which version of polygon-edge do you use? @phpmac

I have my own evm private chain. The local computer is normal. However, after the disk space on the server exceeds the limit and the recovery occurs, the service on port 80 cannot be started.

**Comment by phpmac** [comment] 2024-05-08 16:05
I haven’t looked at the specific reasons yet.

**Comment by sl1depengwyn** [comment] 2024-06-07 16:29
Duplicate of https://github.com/blockscout/blockscout/issues/8647

**Closed by sl1depengwyn** 2024-06-07 16:29 UTC
Labels: triage
