### ISSUE TITLE
Ethereum Classic: No Read / Write tabs for newly published contracts

### ISSUE THREAD

**Issue by MaksimMakrushin** [blockscout/blockscout#4638] opened 2021-09-13 08:44 UTC
For five days now, blockscout has not displayed new transactions. And only empty blocks are created. While the balance of addresses is displayed correctly. The main problem is that the newly published contracts do not display the Read / Write tabs, I would like this functionality to be available. Please clarify when these problems will be fixed?

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36`

### Steps to reproduce

Publish a new smart contract with public fields and viewable functions.

### Expected Behaviour

Read / Write tabs visible.

### Actual Behaviour

No Read / Write tabs when viewing a contract at its address in blockscout.

**Comment by vbaranov** [comment] 2021-09-13 08:51
This is a duplicate of https://github.com/blockscout/blockscout/issues/4627

**Comment by vbaranov** [comment] 2021-09-14 11:49
The issue with indexing has been resolved.

**Closed by vbaranov** 2021-09-14 11:49 UTC
Labels: duplicate, chain: ETC :chains:
