### ISSUE TITLE
application=indexer fetcher=pending_transaction step=import [error] Failed to validate

### ISSUE THREAD

**Issue by kajowy** [blockscout/blockscout#6672] opened 2023-01-05 13:01 UTC
Indexing blockchain is extremely slow. There are a lot of errors saying:
`application=indexer fetcher=pending_transaction step=import [error] Failed to validate` (log attached)

We have a dedicated erigon archive node for the indexer.

Setup:
- Erigon archive node version 2.31.0-stable, running on m6a.8xlarge instance (32vCPU, 128G RAM)
- Blockscout 4.1.8, running on c6a.8xlarge instance (32vCPU, 64G RAM)
- Ethereum mainnet
- default environment variables with adjusted memory limits
- RDS Postgres instance db.m6i.4xlarge (16vCPU, 64G RAM)

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24, Elixir 1.13.1
* Node JS version (`node -v`): v16.13.1
* Operating System: Alpine Linux v3.15
* Blockscout Version/branch/commit: 4.1.8
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Erigon

### Steps to reproduce

Start indexing, and an error will pop up after a while. The indexing speed slows down to a few blocks indexed per minute.

### Expected behavior

No errors in the log. Indexer indexing blockchain with decent speed.

### Actual behavior
Indexing slows down and almost stops. One can see many errors related to validation:
[a.log](https://github.com/blockscout/blockscout/files/10352317/a.log)

**Comment by phoneix1221** [comment] 2023-01-05 15:21
I am facing same issue did you find any resolution to the issue?

**Comment by kajowy** [comment] 2023-01-11 10:33
bump?

**Comment by arccos2x** [comment] 2023-01-11 13:19
would this have to do with eth moving to POS?

**Comment by vbaranov** [comment] 2023-01-11 18:05
@kajowy is `ETHEREUM_JSONRPC_VARIANT=erigon` set?

**Comment by kajowy** [comment] 2023-01-11 18:07
> @kajowy is `ETHEREUM_JSONRPC_VARIANT=erigon` set?

Yes, I've checked all env vars, and they are correctly set

**Comment by vbaranov** [comment] 2023-01-11 18:08
Do you have `ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE=geth`? If not, could you set?

**Comment by phoneix1221** [comment] 2023-01-12 04:05
> Reference in n

Tried facing same issue

**Comment by phoneix1221** [comment] 2023-01-12 04:06
> Do you have `ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE=geth`? If not, could you set?

Tried facing same issue

**Comment by kajowy** [comment] 2023-01-12 08:24
> Do you have `ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE=geth`? If not, could you set?

Same error, I tried to set it to `geth` and `erigon`.

**Comment by phoneix1221** [comment] 2023-01-12 17:28
@vbaranov The problem is in Blockscout gasprice is required i guess but when i look at response of tx_pool of ergion rpc some of the transacations dosen't have gasprice key in the object

**Comment by vbaranov** [comment] 2023-01-12 17:33
Could you post the full response from txpool_content request, which cause the issue?

**Comment by phoneix1221** [comment] 2023-01-12 18:35
@vbaranov  here is the link https://drive.google.com/file/d/1sHUNhH_U32nFzd_dhbrER3xvU3Va3_mz/view?usp=share_link

**Comment by kajowy** [comment] 2023-01-17 12:56
@vbaranov, any luck looking at this?

**Comment by phoneix1221** [comment] 2023-01-19 18:35
@kajowy can you also share the how fast your mainnet sync is with blockscout and your configs?

**Closed** 2023-04-17 10:19 UTC
Labels: waiting on feedback
