### ISSUE TITLE
Awesome chain: <Issue Title>

### ISSUE THREAD

**Issue by volcano7** [blockscout/blockscout#8150] opened 2023-08-08 14:12 UTC
NFT metadata cached once and never updated again.

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce
Connect NFT token. Change in his contract, for example, the path to the metadata.

### Expected Behaviour
The path in example above should be updated.

### Actual Behaviour
The path remains the same.

**Comment by sl1depengwyn** [comment] 2023-08-10 19:42
Duplicate of #7670

**Closed by sl1depengwyn** 2023-08-10 19:42 UTC
