### ISSUE TITLE
State changes not correct when there are internal transactions

### ISSUE THREAD

**Issue by XterioTech** [blockscout/blockscout#9949] opened 2024-04-25 08:01 UTC
### Description

When there are internal transactions transferring ETH in a transaction, the `State` tab does not display correct state changes.
Take this transaction as an example:
https://etherscan.io/tx/0x1321565ad8f6be17f0e16db99dfc75f2334cd475398244a2de56bdfa62f04030#statechange
https://eth.blockscout.com/tx/0x1321565ad8f6be17f0e16db99dfc75f2334cd475398244a2de56bdfa62f04030?tab=state

For ETH transfer, etherscan shows clearly the value flow is as following:
<img width="874" alt="image" src="https://github.com/blockscout/blockscout/assets/106751507/759fe8fa-998d-4be4-a628-3cdcfca5983c">
* 0x3748...8D0C -> _0xFC175...96a7_ 0.7438 ETH
* _0xFC175...96a7_ -> 0x0EAE...3Cb9 0.03719 ETH
* _0xFC175...96a7_ -> 0x7b61...7F49 0.70661 ETH
And in the `State` tab, eitherscan shows correct balance changes:
<img width="1381" alt="image" src="https://github.com/blockscout/blockscout/assets/106751507/09ae442b-ea06-4d0d-9208-88ffc8cf087c">

While in blockscout explorer, the `State` tab shows wrong state changes:
<img width="1442" alt="image" src="https://github.com/blockscout/blockscout/assets/106751507/eb4cb6e1-14bb-4282-9182-0756b1019106">
Note that it shows the balance of 0xFC175...96a7 (Contract) increase by 0.7438, but it does not actually. While the balance increase of 0x0EAE...3Cb9 and 0x7b61...7F49 do not show up in the state changes.

BTW, it's very necessary to display these kind of ETH value transfers within the internal tx on the Detail page like what etherscan does. Especially in some case the smart contract refunds some ETH back to users (e.g. when the payment including slippage tolerance part), without such displaying, users may thought they paid the total value and did not get any refunding.
For now, in the above situation, user can be even more confused since the `State` tab shows wrong changes.
In this following transaction on our gaming L2 testnet:
https://testnet.xterscan.io/tx/0x4caa89f683d6ce508672ec7339b2c7d8b57e90483f76e73099033f903eff94ba
The user pays 0.0902 BNB to the smart contract and get 0.0451 BNB refunding, but the `State` tab shows his balance decreases by 0.0902 BNB + Gas consumed.
<img width="1438" alt="image" src="https://github.com/blockscout/blockscout/assets/106751507/bcf62736-8495-4b2a-a20b-d2ff3a141cd7">
<img width="1458" alt="image" src="https://github.com/blockscout/blockscout/assets/106751507/4e700fb0-4834-468f-bb51-82705ff05b98">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v6.1.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by sl1depengwyn** [comment] 2024-04-28 22:44
Duplicate of https://github.com/blockscout/blockscout/issues/8647

**Closed by sl1depengwyn** 2024-04-28 22:44 UTC
Labels: triage
