### ISSUE TITLE
Support Multi-File Contract Source Code Verification

### ISSUE THREAD

**Issue by mudgen** [blockscout/blockscout#3587] opened 2021-01-24 19:23 UTC
I deployed a contract that is in active use that I cannot verify the source code of using Blockscout because it cannot verify the source code of mult-file contracts.

Flattening the source code of this contract does not work because in some of the files `pragma experimental ABIEncoderV2;` is used and in some files it is not used.   Flattening the contract makes `pragma experimental ABIEncoderV2;` used everywhere which changes the bytecode.

Etherscan supports verifying multi-file contracts and I am able to deploy my contract to Ethereum and verify it using their multi-file source code verification feature.

But I can't use Etherscan because I am using Matic Network which uses Blockscout.   Can Blockscout add support for verifying multi-file contracts?

Related to this issue: #2713

**Comment by vbaranov** [comment] 2021-01-25 15:22
Duplicate of https://github.com/poanetwork/blockscout/issues/3211

**Comment by vbaranov** [comment] 2021-12-30 12:51
Blockscout now supports verification without source flattening through Standard JSON Input #4908. It has been added to https://github.com/blockscout/blockscout/releases/tag/v4.1.0-beta release.

**Closed by vbaranov** 2021-12-30 12:51 UTC
Labels: duplicate
