### ISSUE TITLE
Getting 500 Internal server error while verifying smart contract. Blockscout Deployed on own server.

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6885] opened 2023-02-14 04:54 UTC
<img width="937" alt="Screenshot 2023-02-14 at 10 23 29 AM" src="https://user-images.githubusercontent.com/110845434/218642756-310e58a4-2a7d-4f8a-88f2-91a3276dd1c4.png">

**Comment by vbaranov** [comment] 2023-02-14 06:29
Could you please pull updates from master branch, if not yet? Have you run rs smart-contract verifier service? Could you provide Blockscout logs describing the error?

**Comment by martianacademy** [comment] 2023-02-14 06:30
I didnot find any error in logs, and I think smart-contract-service should
run with docker-compose up command....

**Comment by martianacademy** [comment] 2023-02-14 06:31
Smart contract verifier container is running...

**Comment by vbaranov** [comment] 2023-02-14 06:33
Please pull updates and restart the containers. Try to reproduce the issue and please provide full Blockscout log from the instance.

**Comment by martianacademy** [comment] 2023-02-14 06:34
Ok...

**Comment by vbaranov** [comment] 2023-02-15 13:09
@martianacademy is issue resolved?

**Comment by martianacademy** [comment] 2023-02-15 13:14
Not yet with previous build.... Will try with v5.1 again tommorrow

**Comment by martianacademy** [comment] 2023-02-16 08:19
yes i tried it again with v5.1 but found that

smart-contract-verifier & blockscout/visualizer:latest both have same port

**Comment by vbaranov** [comment] 2023-02-16 10:08
Yes, sorry. Fixed in https://github.com/blockscout/blockscout/pull/6912. @martianacademy Could you pull updates and re-try?

**Comment by martianacademy** [comment] 2023-02-16 10:29
Thanks

**Comment by vbaranov** [comment] 2023-02-17 13:51
@martianacademy does issue still exist after re-try?

**Comment by martianacademy** [comment] 2023-02-17 14:04
I retry but same issue was still there. I will try again after removing
previous containers & images again.... Will let's your know withing 1
hours....

**Comment by martianacademy** [comment] 2023-02-17 15:40
still getting the same error.

**Comment by martianacademy** [comment] 2023-02-17 15:40
blockscout                 | 2023-02-17T15:39:55.512 application=plug
request_id=F0Sm1RvEEUdeOF0AAD5i [info] GET
/address/0x7F9fD63932babC508FAD2f324EB534D09cfE86F0/contract_verifications/new

**Comment by martianacademy** [comment] 2023-02-17 15:42
blockscout                 |         (block_scout_web 5.1.0)
lib/block_scout_web/controllers/address_contract_verification_controller.ex:1:
BlockScoutWeb.AddressContractVerificationController.action/2

blockscout                 | 2023-02-17T15:41:23.355 application=phoenix
[info] CONNECTED TO BlockScoutWeb.UserSocket in 84µs

blockscout                 |   Transport: :websocket

blockscout                 |   Serializer: Phoenix.Socket.V2.JSONSerializer

blockscout                 |   Parameters: %{"locale" => "en", "vsn" =>
"2.0.0"}


these are the full logs

**Comment by martianacademy** [comment] 2023-02-17 16:54
should I post the env variables I am using, I dont think any sensitive
information is there....

**Comment by vbaranov** [comment] 2023-02-17 17:07
Yes, please and how did you run both explorer and smart-contract verifier.

**Comment by martianacademy** [comment] 2023-02-17 17:16
# DOCKER_TAG=

ETHEREUM_JSONRPC_VARIANT=geth

ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545/

***@***.***:7432/blockscout?ssl=false

ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/

NETWORK=MyVee

SUBNETWORK=MyVee Blockchain

LOGO=/images/myvee_scan_logo.svg

LOGO_FOOTER=/images/myvee_scan_logo.svg

ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8546

ETHEREUM_JSONRPC_TRANSPORT=http

ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=false

IPC_PATH=

NETWORK_PATH=/

API_PATH=/

SOCKET_ROOT=/

BLOCKSCOUT_HOST=

BLOCKSCOUT_PROTOCOL=

# SECRET_KEY_BASE=

# CHECK_ORIGIN=

PORT=4000

COIN_NAME=MYVEE

# METADATA_CONTRACT=

# VALIDATORS_CONTRACT=

# KEYS_MANAGER_CONTRACT=

# REWARDS_CONTRACT=

# TOKEN_BRIDGE_CONTRACT=

EMISSION_FORMAT=DEFAULT

# CHAIN_SPEC_PATH=

# SUPPLY_MODULE=

COIN=MYVEE

EXCHANGE_RATES_COIN=

# EXCHANGE_RATES_SOURCE=

# EXCHANGE_RATES_COINGECKO_COIN_ID=

# EXCHANGE_RATES_COINGECKO_API_KEY=

# EXCHANGE_RATES_COINMARKETCAP_API_KEY=

POOL_SIZE=90

POOL_SIZE_API=10

ECTO_USE_SSL=false

# DATADOG_HOST=

# DATADOG_PORT=

# SPANDEX_BATCH_SIZE=

# SPANDEX_SYNC_THRESHOLD=

HEART_BEAT_TIMEOUT=30

# HEART_COMMAND=

BLOCKSCOUT_VERSION=Build with Blockscout v5.1.0 -beta

RELEASE_LINK=

BLOCK_TRANSFORMER=base

# GRAPHIQL_TRANSACTION=

# BLOCK_RANGES=

# FIRST_BLOCK=

# LAST_BLOCK=

# TRACE_FIRST_BLOCK=

# TRACE_LAST_BLOCK=

LINK_TO_OTHER_EXPLORERS=false

OTHER_EXPLORERS={}

SUPPORTED_CHAINS={}

CACHE_BLOCK_COUNT_PERIOD=7200

CACHE_TXS_COUNT_PERIOD=7200

CACHE_ADDRESS_COUNT_PERIOD=7200

CACHE_ADDRESS_SUM_PERIOD=3600

CACHE_TOTAL_GAS_USAGE_PERIOD=3600

CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD=1800

CACHE_TOKEN_HOLDERS_COUNTER_PERIOD=3600

CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD=3600

CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=1800

CACHE_AVERAGE_BLOCK_PERIOD=1800

CACHE_MARKET_HISTORY_PERIOD=21600

CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD=1800

CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD=1800

CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD=1800

CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=1800

CACHE_TOKEN_EXCHANGE_RATE_PERIOD=1800

TOKEN_METADATA_UPDATE_INTERVAL=172800

ALLOWED_EVM_VERSIONS=homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,default

UNCLES_IN_AVERAGE_BLOCK_TIME=false

DISABLE_WEBAPP=false

DISABLE_READ_API=false

DISABLE_WRITE_API=false

DISABLE_INDEXER=false

DISABLE_REALTIME_INDEXER=false

DISABLE_TOKEN_INSTANCE_FETCHER=false

INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=false

INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=false

# INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=

# INDEXER_CATCHUP_BLOCKS_CONCURRENCY=

# INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=

# INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=

# INDEXER_COIN_BALANCES_BATCH_SIZE=

# INDEXER_COIN_BALANCES_CONCURRENCY=

# INDEXER_RECEIPTS_BATCH_SIZE=

# INDEXER_RECEIPTS_CONCURRENCY=

# INDEXER_TX_ACTIONS_ENABLE=

# INDEXER_TX_ACTIONS_MAX_TOKEN_CACHE_SIZE=

# INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK=

# INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK=

# INDEXER_TX_ACTIONS_REINDEX_PROTOCOLS=

# TOKEN_ID_MIGRATION_FIRST_BLOCK=

# TOKEN_ID_MIGRATION_CONCURRENCY=

# TOKEN_ID_MIGRATION_BATCH_SIZE=

# INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=

# WEBAPP_URL=

# API_URL=

WOBSERVER_ENABLED=false

SHOW_ADDRESS_MARKETCAP_PERCENTAGE=true

CHECKSUM_ADDRESS_HASHES=true

CHECKSUM_FUNCTION=eth

DISABLE_EXCHANGE_RATES=true

DISABLE_KNOWN_TOKENS=false

ENABLE_TXS_STATS=true

SHOW_PRICE_CHART=true

SHOW_TXS_CHART=true

HISTORY_FETCH_INTERVAL=30

TXS_HISTORIAN_INIT_LAG=0

TXS_STATS_DAYS_TO_COMPILE_AT_INIT=10

COIN_BALANCE_HISTORY_DAYS=90

APPS_MENU=false

EXTERNAL_APPS=[]

# GAS_PRICE=

# RESTRICTED_LIST=

# RESTRICTED_LIST_KEY=

SHOW_MAINTENANCE_ALERT=false

MAINTENANCE_ALERT_MESSAGE=

CUSTOM_CONTRACT_ADDRESSES_TEST_TOKEN=

ENABLE_SOURCIFY_INTEGRATION=false

SOURCIFY_SERVER_URL=

SOURCIFY_REPO_URL=

CHAIN_ID=7878

MAX_SIZE_UNLESS_HIDE_ARRAY=50

HIDE_BLOCK_MINER=false

DISPLAY_TOKEN_ICONS=false

SHOW_TENDERLY_LINK=false

TENDERLY_CHAIN_PATH=

MAX_STRING_LENGTH_WITHOUT_TRIMMING=2040

RE_CAPTCHA_SECRET_KEY=

RE_CAPTCHA_CLIENT_KEY=

JSON_RPC=https://rpc.myveescan.com

#API_RATE_LIMIT_DISABLED=true

API_RATE_LIMIT=50

API_RATE_LIMIT_BY_KEY=50

API_RATE_LIMIT_BY_IP=50

API_RATE_LIMIT_WHITELISTED_IPS=

API_RATE_LIMIT_STATIC_API_KEY=

FETCH_REWARDS_WAY=trace_block

ENABLE_RUST_VERIFICATION_SERVICE=true

RUST_VERIFICATION_SERVICE_URL=http://smart-contract-verifier:8050/

VISUALIZE_SOL2UML_ENABLED=true

VISUALIZE_SOL2UML_SERVICE_URL=http://visualizer:8050/

SIG_PROVIDER_ENABLED=true

SIG_PROVIDER_SERVICE_URL=http://sig-provider:8050/

DECODE_NOT_A_CONTRACT_CALLS=true

# DATABASE_READ_ONLY_API_URL=

# ACCOUNT_DATABASE_URL=

# ACCOUNT_POOL_SIZE=

# ACCOUNT_AUTH0_DOMAIN=

# ACCOUNT_AUTH0_CLIENT_ID=

# ACCOUNT_AUTH0_CLIENT_SECRET=

# ACCOUNT_AUTH0_LOGOUT_URL=

# ACCOUNT_AUTH0_LOGOUT_RETURN_URL=

# ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=

# ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=

# ACCOUNT_SENDGRID_API_KEY=

# ACCOUNT_SENDGRID_SENDER=

# ACCOUNT_SENDGRID_TEMPLATE=

ACCOUNT_CLOAK_KEY=

ACCOUNT_ENABLED=false

ACCOUNT_REDIS_URL=redis://redis_db:6379

# MIXPANEL_TOKEN=

# MIXPANEL_URL=

# AMPLITUDE_API_KEY=

# AMPLITUDE_URL=

**Comment by vbaranov** [comment] 2023-02-17 17:20
It looks correct, do you see compilers versions list dropdown on the ferifiaction form? What happens when you click "Verify" button?

**Comment by martianacademy** [comment] 2023-02-17 17:21
Process of starting blockscout:

1. cd blockscout/docker-compose
2. docker-cmpose up --build -d

Output after build

Starting sig-provider            ... done

Starting postgres                ... done

Starting redis_db                ... done

Starting visualizer              ... done

Starting smart-contract-verifier ... done

Starting blockscout              ... done

Output docker ps

CONTAINER ID   IMAGE
COMMAND                  CREATED         STATUS          PORTS
                              NAMES

afcc83408847   blockscout/blockscout:latest                      "bash
-c 'bin/blocks…"   5 minutes ago   Up 31 seconds
0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   blockscout

cf7dff86f389   postgres:14
"docker-entrypoint.s…"   5 minutes ago   Up 32 seconds
0.0.0.0:7432->5432/tcp, :::7432->5432/tcp   postgres

e8f2143ff572   ghcr.io/blockscout/smart-contract-verifier:main
"./smart-contract-ve…"   5 minutes ago   Up 32 seconds
0.0.0.0:8150->8050/tcp, :::8150->8050/tcp   smart-contract-verifier

79765d032378   ghcr.io/blockscout/visualizer:latest
"./visualizer-server"    5 minutes ago   Up 32 seconds
0.0.0.0:8152->8050/tcp, :::8152->8050/tcp   visualizer

d0c92be129b4   ghcr.io/blockscout/sig-provider:main
"./sig-provider-serv…"   5 minutes ago   Up 32 seconds
0.0.0.0:8151->8050/tcp, :::8151->8050/tcp   sig-provider

37b3e6b476c3   redis:alpine
"docker-entrypoint.s…"   5 minutes ago   Up 32 seconds
0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   redis_db

9be9388ea6a2   myvee/ethstats                                    "npm
start"              4 days ago      Up 4 days
0.0.0.0:8080->3000/tcp, :::8080->3000/tcp   myvee_ethstats_1

this is the whole story.

at last running in digital ocean:

8 GB Memory / 160 GB Disk / BLR1 - Ubuntu 20.04 (LTS) x64

with this configurations. Firewall settings attached.

**Comment by martianacademy** [comment] 2023-02-17 17:22
where I get this?

**Comment by vbaranov** [comment] 2023-02-17 17:28
Your issue is about 500 error on contract verification. Do you still have this issue? Were you able to verify contract? If not, what error in the logs?

**Comment by martianacademy** [comment] 2023-02-17 17:29
yes this is the issue

**Comment by martianacademy** [comment] 2023-02-17 17:29
just installed the latest release and run the above.

**Comment by vbaranov** [comment] 2023-02-17 17:31
Ok, describe how you verify contract ste by step. Attach screenshots of the verification form.

**Comment by martianacademy** [comment] 2023-02-17 17:37
Open Contract page
<img width="1296" alt="Screenshot 2023-02-17 at 11 05 34 PM" src="https://user-images.githubusercontent.com/110845434/219728267-b81ea819-012a-4574-8305-eb5292f840d3.png">

Click on Code
<img width="1296" alt="Screenshot 2023-02-17 at 11 05 45 PM" src="https://user-images.githubusercontent.com/110845434/219728412-0832b7be-7703-4d32-ba52-3b5cb595a9b1.png">

Click on verify & publish and get 500 error
<img width="1387" alt="Screenshot 2023-02-17 at 11 06 03 PM" src="https://user-images.githubusercontent.com/110845434/219728652-7b1a4df9-0512-459c-9b25-3f55e05b0fbe.png">

**Comment by martianacademy** [comment] 2023-02-17 17:38
These are my inbound rules
<img width="1387" alt="Screenshot 2023-02-17 at 11 08 11 PM" src="https://user-images.githubusercontent.com/110845434/219729079-7dd7ff68-e531-4304-8ac2-6e75cd758578.png">

These are my outbound rule
<img width="1387" alt="Screenshot 2023-02-17 at 11 08 40 PM" src="https://user-images.githubusercontent.com/110845434/219729271-dca9613d-f9b5-42db-8dab-18b4a760b64b.png">

**Comment by martianacademy** [comment] 2023-02-17 17:45
ok wait

**Comment by martianacademy** [comment] 2023-02-17 17:51
This is the error repeating itself:

2023-02-17T17:35:47.285 [error] #PID<0.12177.0> running
BlockScoutWeb.Endpoint (connection #PID<0.12176.0>, stream id 1) terminated

Server: localhost:4000 (http)

Request: GET
/address/0x7F9fD63932babC508FAD2f324EB534D09cfE86F0/contract_verifications/new

** (exit) an exception was raised:

    ** (ArgumentError) cookie store expects conn.secret_key_base to be set

        (block_scout_web 5.1.0)
lib/block_scout_web/plug/redis_cookie.ex:127:
BlockScoutWeb.Plug.RedisCookie.validate_secret_key_base/1

        (block_scout_web 5.1.0)
lib/block_scout_web/plug/redis_cookie.ex:122:
BlockScoutWeb.Plug.RedisCookie.derive/3

        (block_scout_web 5.1.0)
lib/block_scout_web/plug/redis_cookie.ex:39:
BlockScoutWeb.Plug.RedisCookie.put/4

        (plug 1.14.0) lib/plug/session.ex:96: anonymous fn/3 in
Plug.Session.before_send/2

        (elixir 1.13.1) lib/enum.ex:2396:
Enum."-reduce/3-lists^foldl/2-0-"/3

        (plug 1.14.0) lib/plug/conn.ex:1839: Plug.Conn.run_before_send/2

        (plug 1.14.0) lib/plug/conn.ex:448: Plug.Conn.send_resp/1

        (block_scout_web 5.1.0)
lib/block_scout_web/controllers/address_contract_verification_controller.ex:1:
BlockScoutWeb.AddressContractVerificationController.action/2

**Comment by vbaranov** [comment] 2023-02-17 17:57
I see now. This is the issue
> ** (ArgumentError) cookie store expects conn.secret_key_base to be set

You need to add `SECRET_KEY_BASE` env var and put a secret there (alpha-numberic sequence)

**Comment by martianacademy** [comment] 2023-02-17 17:59
ok should I put in blockscout/docker-compose/envs/common-blockscout.env

**Comment by martianacademy** [comment] 2023-02-17 18:00
Ya I got it.... it is looking for a api secret? Am I right?

**Comment by vbaranov** [comment] 2023-02-17 18:09
Yes, it is already there, but commented and without value.

**Comment by martianacademy** [comment] 2023-02-17 18:11
I put some value there but still the same error. I checked the docs and
found this:

SECRET_KEY_BASE Use mix phx.gen.secret to generate a new Secret Key Base
string to protect production assets.

How to generate the

**Comment by vbaranov** [comment] 2023-02-17 18:20
Did you restart containers? You can connect to blockscout container and run `mix phx.gen.secret` there, then set this value in .env file and restart containers.

**Comment by martianacademy** [comment] 2023-02-17 18:50
Yes done now... but not able to generate the secret...

**Comment by vbaranov** [comment] 2023-02-17 19:03
Your issue resolved after restarting containers

**Closed by vbaranov** 2023-02-17 19:03 UTC
Labels: waiting on feedback

**Comment by martianacademy** [comment] 2023-02-17 19:14
issue resolved but using the secret_key provided in your tutorial... was
unable to generate the secret_key from container..... but issue resolved
for now... will learn more about mix commands for production build.

**Comment by martianacademy** [comment] 2023-02-17 20:28
I just verified a smart contract successfully. One last favour... how could
I generate api_key so that I can verify smart contract from hardhat ?

**Comment by vbaranov** [comment] 2023-02-17 22:50
Leave it empty. You don't need api key for verification with Blocskcout.

**Comment by Osub** [comment] 2023-08-01 10:14
me too

**Comment by mpekhota** [comment] 2024-04-11 13:23
I have the same issue with error 500. I just verified a smart contract successfully, but I can't read contract using "Read contract" button. 
I can't generate SECRET_KEY_BASE in blockscout-stack-blockscout pod because I getting an error "** (Mix) The task "phx.gen.secret" could not be found
Note no mix.exs was found in the current directory"
Any ideas?

Versions: Helm chart v1.5.0
Blockscout v6.4.0-beta
Frontend: v1.28.1
