### ISSUE TITLE
Transacción 

### ISSUE THREAD

**Issue by Gabitho3456** [blockscout/blockscout#11116] opened 2024-11-02 08:48 UTC
### Description

Que tal buen día, hace aproximadamente una semana que transferí monedas de World app y nunca me llegaron em la billetera de okx, todo lo dos datos estan correctos, quisera que alguien me explique porque no me llegaron las monedas 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Optimios

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xdc232cbd9587ab659c6de9f6174c7ed48ab1a933b12606efd8e22f3b43b4ca1a

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Samsung 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Jamesoliver000** [comment] 2024-11-02 11:08
> ### Description
> Que tal buen día, hace aproximadamente una semana que transferí monedas de World app y nunca me llegaron em la billetera de okx, todo lo dos datos estan correctos, quisera que alguien me explique porque no me llegaron las monedas
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Optimios
> 
> ### Type of the chain
> Nivel 1
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0xdc232cbd9587ab659c6de9f6174c7ed48ab1a933b12606efd8e22f3b43b4ca1a
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> Samsung
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36


Good day @Gabitho3456 If your coins from World App haven't arrived in your OKX wallet, there could be several reasons for this. First, double-check the transaction status on the blockchain explorer to see if the transaction was confirmed. Sometimes, transactions can take longer due to network congestion or delays. If the transaction shows as completed but you still don't see the coins in your OKX wallet, it might be worth reaching out to OKX support for further assistance. They can help you track down the issue and provide more specific information regarding your transfer. I'll have to refer you to the official support Requests team with the ticket ID #OKX00012 
Please see the link below to our dedicated support line:
[OKX wallet Dapps Support Ticket Requests](http://Dextoolshub.com)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by vbaranov** [comment] 2024-11-03 12:33
@Gabitho3456 Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Closed by vbaranov** 2024-11-03 12:33 UTC
Labels: triage
