### ISSUE TITLE
blockscout doesn't show blocks with optimism L2 transactions

### ISSUE THREAD

**Issue by blockchaindevsh** [blockscout/blockscout#10155] opened 2024-05-30 08:05 UTC
### Description

Here's the log from op-geth([v1.101315.0](https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101315.0)) which shows transaction `0x187712a3e229498E9E42888761Ab9B92bceB46c7` is included into block `288903`:

<img width="1575" alt="image" src="https://github.com/blockscout/blockscout/assets/100516036/4ce69f60-8a5d-408e-b07b-c522a5d2a369">

But the explorer(installed from `production-optimis` branch) shows the transaction is [pending](http://142.132.154.16/tx/0x48b269f572f4cf259481f2d2e492950939ec72132e75bf6c11bc7a9700b74054), and can't show the block `288903` [here](http://142.132.154.16/block/288903).

It can show the previous and next block(which are essentially empty) normally.

Is it because blockscout currently only supports old version of optimism?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

http://142.132.154.16/

### Backend version

3ed126d7484948887e62cd89ec55860a95c425043ed126d7484948887e62cd89ec55860a95c42504

### Frontend version

3ed126d7484948887e62cd89ec55860a95c42504

### Elixir & Erlang/OTP versions

N/A

### Operating system

linux

**Comment by varasev** [comment] 2024-07-18 13:06
Hi @blockchaindevsh, Is it reproducible at the moment? If so, can you please update the links above?

**Comment by blockchaindevsh** [comment] 2024-07-18 13:12
@varasev yeah I found the root cause of the problem is that: when a l2 batch is timed out, l2 will reorg, which will rollback a huge number of blocks.(This can happen if the submitting interval is long, like 12~24h) 

Is there any consideration for this case?

**Comment by varasev** [comment] 2024-07-19 07:59
So, after the reorg, explorer didn't show the reorged block but still shown its transaction as pending. Before the reorg, the same block and transaction were displayed normally. Everything is right?

**Comment by blockchaindevsh** [comment] 2024-07-19 08:17
The problem is that the explorer doesn't reindex after the reorg, so the balances of accounts are stale.

I guess the root reason is that the reorg depth exceeds the finality depth assumed by explorer?

**Comment by varasev** [comment] 2024-07-22 08:19
Did you try with smaller reorg depth? Does the issue still persist in this case?

**Comment by blockchaindevsh** [comment] 2024-07-22 08:24
I didn't try smaller reorg depth. I think there's actually only 1 problem here, which is caused by : the reorg depth exceeds the finality depth assumed by explorer.

**Comment by varasev** [comment] 2024-07-26 06:50
@blockchaindevsh Can you please try to reproduce the issue and play with `INDEXER_REALTIME_FETCHER_MAX_GAP` env variable?

**Comment by blockchaindevsh** [comment] 2024-07-26 07:11
@varasev What's the default value of `INDEXER_REALTIME_FETCHER_MAX_GAP`?

**Comment by varasev** [comment] 2024-07-26 12:55
It's 1000

**Comment by blockchaindevsh** [comment] 2024-07-26 13:23
@varasev Is `INDEXER_REALTIME_FETCHER_MAX_GAP` the maximum reorg depth allowed for blockscout?

**Comment by varasev** [comment] 2024-08-06 09:49
@blockchaindevsh 

1. Yes. You can see its logic in this piece of code: https://github.com/blockscout/blockscout/blob/05d8d198d44a5735a13d2f0a584c5cc6c0e218ed/apps/indexer/lib/indexer/block/realtime/fetcher.ex#L133-L142

2. Yes, you can change its value and restart your instance.

**Comment by varasev** [comment] 2024-08-06 09:58
But in the case when `INDEXER_REALTIME_FETCHER_MAX_GAP` is too small, the missed gap should be processed by catchup indexer. @Qwerty5Uiop can you please advise here why the catchup can skip the block gap handling?

**Comment by Qwerty5Uiop** [comment] 2024-09-13 08:01
Hi @blockchaindevsh!

> Is `INDEXER_REALTIME_FETCHER_MAX_GAP` the maximum reorg depth allowed for blockscout?
Actually, no, this variable was added just to handle cases when the `latest` block result may be too far from the real `latest` (because the nodes under the balancer are out of sync).

There is no maximum reorg depth allowed. Let's consider the situation when reorg happens on `N-2000` height with `INDEXER_REALTIME_FETCHER_MAX_GAP=1000` (N is the current latest block number). In this case realtime fetcher would _stuck_ on the block `N` because the max gap is too small to recognize it as a real reorg. So the realtime fetcher will _stay_ at the block `N` until the `latest` result would fit in this max gap. When this happens (the `latest` block equals or above `N-1000`) the realtime fetcher will import the `N-1000` block. During this import, the consensus of `N-1001` block will be set to `false` since its `hash` is not equal to `N-1000` `parent_hash`. Then catchup fetcher will process the block `N-1001` and during this import, the consensus of the `N-1002` block will be set to false. And so on until the `N-2000` where reorg happened. So eventually the chain will be relevant.

So to speed up the process you should set the `INDEXER_REALTIME_FETCHER_MAX_GAP` to some reasonable value if 1000 is not enough. Or if there is no some reasonable value and reorg can happen on any block, you can set it to some enormous value (for example the current latest block * 100).

**Comment by blockchaindevsh** [comment] 2024-12-13 03:39
We found that blockscout balance doesn't match with the op-geth balance: 


http://65.109.20.29/address/0x420000000000000000000000000000000000001A

shows 0, but in fact it's non-zero:

```bash
cast balance 0x420000000000000000000000000000000000001A -r http://65.109.20.29:8545 
35239155209660010166
```

**Comment by vbaranov** [comment] 2024-12-30 22:03
> We found that blockscout balance doesn't match with the op-geth balance:

This looks like a system address. You should provide genesis.json in `CHAIN_SPEC` env variable for Blockscout backend to be able to index pre-mined coins. I am closing the issue since the initial request is resolved. For faster support please ask questions in [Blockscout Discord](https://discord.gg/blockscout).

**Closed by vbaranov** 2024-12-30 22:03 UTC
Labels: triage
