### ISSUE TITLE
Verification of contracts with constructors from genesis block fails

### ISSUE THREAD

**Issue by twt--** [blockscout/blockscout#3447] opened 2020-11-12 02:34 UTC
Verifying contracts from the genesis block works only if they do not have a constructor.  Contracts with a constructor fail to verify.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 22 [erts-10.7.2.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]
Elixir 1.10.4 (compiled with Erlang/OTP 22)
* Operating System: Debian Buster
* Blockscout Version/branch: v3.3.3-beta

### Steps to reproduce

I'm using https://github.com/poanetwork/posdao-contracts/blob/master/scripts/make_spec.js to generate a chain spec file, then trying to verify those contracts in blockscout.  The contracts without constructors verify as expected, but the contracts with constructors (AdminUpgradeabilityProxy & Initializer) fail verification with an invalid constructor arguments error.

Modifying [Explorer.Chain.contract_creation_input_data](https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/chain.ex#L3156) to return `Data.to_string(transaction.contract_code)` when it fails to lookup the data from the transaction fixes it for me, but I'm not sure if that's a proper solution.

### Expected behaviour

Contract verification succeeds

### Actual behaviour

Contract verification fails with invalid constructor arguments error.

**Comment by vbaranov** [comment] 2020-11-12 06:38
@twt-- Did you try to verify with UI or API endpoint? Did you set constructor arguments manually or use constructor arguments auto-detection option?

**Comment by twt--** [comment] 2020-11-12 06:45
Tried with both UI & API, and both specifying arguments and auto detection - neither worked.
When modifying Explorer.Chain.contract_creation_input_data to get it working, I only tested with specifying constructor arguments

**Comment by vbaranov** [comment] 2020-11-23 10:31
@twt-- Thank you for the details. I reproduced and fixed verification of precompiled contracts in this PR https://github.com/poanetwork/blockscout/pull/3476. It was merged to master branch. Could you use the latest master branch and let me know if the issue is resolved on your side?

**Closed** 2021-08-20 08:56 UTC
Labels: waiting on feedback, contract verification
