### ISSUE TITLE
Mumbai: <Payable functions can't be called from the explorer>

### ISSUE THREAD

**Issue by safebeez** [blockscout/blockscout#4171] opened 2021-05-30 00:52 UTC
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

Call a payable function from your explorer, it converts the int into hexdecimal

### Expected Behaviour

it should not convert int into hexdecimal, it should do the same as BSC scan, and ether scan

### Actual Behaviour

it fails

**Comment by vbaranov** [comment] 2021-06-04 08:41
@safebeez we have no official support of Polygon/Matic. Please provide steps on how to reproduce the issue in xDai/Sokol instances of BlockScout: https://blockscout.com/xdai/mainnet / https://blockscout.com/poa/sokol

**Comment by alexstronghand** [comment] 2021-06-09 07:09
I have the same issue with Blockscout's Polygon explorer.

Payable functions shows up an error. Here is a simple testnet contract to demonstrate the bug:
https://polygon-explorer-mumbai.chainstacklabs.com/address/0x0BFE0fdf714ef900d0F3F63194E84A99a0Caad35/write-contract

Try using updateVarAndSendETH to send value(ETH) and the frontend interface throws up an error message.

**Comment by vbaranov** [comment] 2023-06-20 12:37
Closing due to explorer doesn't work on the link above. Let us know if you still experience the issues.

**Closed by vbaranov** 2023-06-20 12:37 UTC
Labels: waiting on feedback
