### ISSUE TITLE
Precompile contract verification

### ISSUE THREAD

**Issue by bulbazavr1024** [blockscout/blockscout#7778] opened 2023-06-23 13:34 UTC
*Describe your issue here.*

### Environment

* Deployment type: Docker-compose:
* Elixir & Erlang/OTP versions (`elixir -version`): latest
* Node JS version (`node -v`):
* Operating System: ubuntu 22.0.4
* Blockscout Version/branch/commit: master
* Archive node type && version: Geth

@vbaranov Hey! I want to add precompile contract code to blockscout. 
I have chain, that implement Cosmos core logic and Geth EVM. (e.x. EVMOS). There is deployed precompile contract to address   
0x1559000000000000000000000000000000000001 in Cosmos.
 EXTCODESIZE == 0, and this contract hasn't deploy transaction emitted to EVM part. 
 How can I add contract source code manually ? 
 
 If I try to INSERT it to smart_contracts table I receive ERROR: insert or update on table "smart_contracts" violates foreign key constraint "smart_contracts_address_hash_fkey"
 
 But I have address 0x1559000000000000000000000000000000000001 in addresses table 
![image](https://github.com/blockscout/blockscout/assets/77885154/825b2ed1-c9c1-43b2-a027-dca73c0aecdd)

What is the best practice of it ?

**Comment by sl1depengwyn** [comment] 2023-06-26 12:48
I think the best way to do this is to pass path to your genesis/chain spec via `CHAIN_SPEC_PATH` env 
But, if this is not applicable to you by any reason, you need to insert contract bytecode to `contract_code` column in **`addresses`** table

**Comment by bulbazavr1024** [comment] 2023-06-26 18:18
@sl1depengwyn Thanks! Will try in a short time

**Comment by vbaranov** [comment] 2023-07-17 16:40
@bulbazavr1024 did the last suggestion resolve the issue?

**Comment by bulbazavr1024** [comment] 2023-07-17 16:41
@vbaranov Hey! Sorry for the delay.
I was on vacation and couldn't check it.  I will give you an answer tomorrow

**Comment by vbaranov** [comment] 2023-07-26 13:02
@bulbazavr1024 I am closing this. Please let us know, if the issue is still reproducible on your side.

**Closed by vbaranov** 2023-07-26 13:02 UTC
Labels: waiting on feedback
