### ISSUE TITLE
Wrong miner address with latest geth poa(clique)

### ISSUE THREAD

**Issue by masayil** [blockscout/blockscout#5380] opened 2022-03-28 15:34 UTC
![image](https://user-images.githubusercontent.com/65291464/160433690-280e79c6-31a0-4d0a-9fcb-ea55d84c3d69.png)
The miner address is random. It should be 0x000.....000.
![image](https://user-images.githubusercontent.com/65291464/160434147-55430054-adfb-4af0-8e1d-fdfb75ca7432.png)
Is this a bug?

**Comment by vbaranov** [comment] 2022-03-29 13:50
Duplicate of https://github.com/blockscout/blockscout/issues/5065

**Closed** 2022-04-17 11:23 UTC
Labels: duplicate
