### ISSUE TITLE
(FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.PolygonTracer.replay

### ISSUE THREAD

**Issue by dorijan** [blockscout/blockscout#8437] opened 2023-09-11 12:07 UTC
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose with [5.2.2.commit.ca3886d6]
* Operating System: ubuntu 22.04
* Blockscout Version/branch/commit: 5.2.2.commit.ca3886d6
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge 1.1+ (build from latest source)
*

### Steps to reproduce

-run brand new chain on polygon-edge using scripts/cluster polybft
-connect to rpc
-got this error in error messages:

```
blockscout               | 2023-09-11T12:00:56.452 application=indexer fetcher=internal_transaction count=7 error_count=7 [error] failed to fetch internal transactions for blocks: ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.PolygonTracer.replay/3
blockscout               |     (ethereum_jsonrpc 5.2.2) lib/ethereum_jsonrpc/geth/polygon_tracer.ex:11: EthereumJSONRPC.Geth.PolygonTracer.replay(%{"failed" => false, "gas" => 21000, "returnValue" => "", "structLogs" => nil}, %{"blockHash" => "0xa6ffd362765a547a97b8375ed7adb3fd2f83eb2532573b55d403956fcee3f23e", "blockNumber" => "0x2c", "contractAddress" => nil, "cumulativeGasUsed" => "0x5208", "from" => "0x7F486924FB57952aa827B773E7C1cF2EEED160e3", "gasUsed" => "0x5208", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root" => "0x0000000000000000000000000000000000000000000000000000000000000000", "status" => "0x1", "to" => "0x69cFaE16cAD702fDcEcd1c0487d8dbc084cffCF3", "transactionHash" => "0x9315a23510606c9d9a5a02a3621f82cc675195b2245fb3038166eff1f7cd2350", "transactionIndex" => "0x0"}, %{"blockHash" => "0xa6ffd362765a547a97b8375ed7adb3fd2f83eb2532573b55d403956fcee3f23e", "blockNumber" => "0x2c", "chainId" => "0x64", "from" => "0x7F486924FB57952aa827B773E7C1cF2EEED160e3", "gas" => "0x5208", "gasPrice" => "0x5994e7b9", "hash" => "0x9315a23510606c9d9a5a02a3621f82cc675195b2245fb3038166eff1f7cd2350", "input" => "0x", "maxFeePerGas" => "0x59ae471d", "maxPriorityFeePerGas" => "0x59682f00", "nonce" => "0x1", "r" => "0x2459c48bcfe8c972f634da7885f154ef8506e997b6c0abb0a03415085ba8dd30", "s" => "0x296a37ca60feb7b2396f588cab19c5af7ef49371d0fc8bdeb4932cbbfdc821b6", "to" => "0x69cFaE16cAD702fDcEcd1c0487d8dbc084cffCF3", "transactionIndex" => "0x0", "type" => "0x2", "v" => "0x0", "value" => "0xf43fc2c04ee0000"})
blockscout               |     (ethereum_jsonrpc 5.2.2) lib/ethereum_jsonrpc/geth.ex:148: anonymous fn/5 in EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
blockscout               |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (ethereum_jsonrpc 5.2.2) lib/ethereum_jsonrpc/geth.ex:146: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
blockscout               |     (indexer 5.2.2) lib/indexer/fetcher/internal_transaction.ex:206: anonymous fn/3 in Indexer.Fetcher.InternalTransaction.fetch_block_internal_transactions_by_transactions/2
blockscout               |     (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
blockscout               |     (indexer 5.2.2) lib/indexer/fetcher/internal_transaction.ex:119: Indexer.Fetcher.InternalTransaction.run/2
blockscout               |     (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2


```

**Comment by vbaranov** [comment] 2023-09-11 14:02
@dorijan please set `INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=polygon_edge`.

**Comment by dorijan** [comment] 2023-09-11 14:21
> INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE

it was set:

```
cat common-blockscout.env | grep INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE
INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=polygon_edge

```

I now even tried modifing docker-compose-no-build-geth.yml like this, but still got the same error

```
cat docker-compose-no-build-geth.yml | grep INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE 
        INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE: polygon_edge

```

**Comment by sl1depengwyn** [comment] 2023-09-13 06:01
Duplicate of https://github.com/blockscout/blockscout/issues/8353

**Closed by sl1depengwyn** 2023-09-13 06:01 UTC
Labels: waiting on feedback
