### ISSUE TITLE
TX State update issues

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#8403] opened 2023-09-06 12:49 UTC
Environment: https://eth.blockscout.com/
Backend: [v5.2.2-beta.+commit.b4c0ab85](https://github.com/blockscout/blockscout/commit/b4c0ab85)
Frontend: v1.10.0+ea5c9d58

Steps to reproduce (1 time):
1. Open https://eth.blockscout.com/tx/0x89a41ebe0f5ecc2300ecae4c84721c32de2396a6b34dd173ab0f15ccb12b5ecc?tab=state and check balances before
2. Refresh the page

![Image](https://user-images.githubusercontent.com/108135703/266011930-6c0743a2-5be1-4104-a735-9832aa4ac12a.png)

![Image](https://user-images.githubusercontent.com/108135703/266011991-d9cebcfc-1534-4fbd-a338-35a64c76991e.png)

Expected behaviour: All balances are updated on first load
Actual behaviour: All balances are updated only after refresh

**Comment by vbaranov** [comment] 2024-01-16 20:39
I am closing this. I cannot reproduce it anymore.

**Closed by vbaranov** 2024-01-16 20:39 UTC
Labels: bug :bug:
