### ISSUE TITLE
Worldcoin funds not recieved in my TrustWallet

### ISSUE THREAD

**Issue by mirol94** [blockscout/blockscout#11289] opened 2024-11-28 13:52 UTC
### Description

Tramsaction is successful, funds have been deducted from my Worldcoin App but it's not showing in my TrustWallet App

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ERC20

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xbe210d5c11d05f15539a6cd29d82902b12bcf5cbe86e2dec5235a84c828479b6

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by consensys-mod** [comment] 2024-11-28 13:58
> ### Description
> Tramsaction is successful, funds have been deducted from my Worldcoin App but it's not showing in my TrustWallet App
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> ERC20
> 
> ### Type of the chain
> L1
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0xbe210d5c11d05f15539a6cd29d82902b12bcf5cbe86e2dec5235a84c828479b6
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.2+f793609b
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.17.3
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Worldchain Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by sl1depengwyn** [comment] 2024-11-28 14:03
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Closed by sl1depengwyn** 2024-11-28 14:03 UTC
Labels: triage
