### ISSUE TITLE
after a swap with apertureswap, I didn't receive my tokens

### ISSUE THREAD

**Issue by hakimm75019** [blockscout/blockscout#9813] opened 2024-04-04 07:55 UTC
### Description

hello, 
yesterday morning I made a swap of 2470 usdc for stone eth with apertureswap, my usdc were transferd but i didn't received any stone. when I asked and opened a ticket with apertureswap team, they confirmed the problem, but they said me to see with blockscout.
![capture blocksout](https://github.com/blockscout/blockscout/assets/156819806/0b1b9b28-f7e0-4816-9ffe-bebac7290a0d)
![capture ecran apertureswap](https://github.com/blockscout/blockscout/assets/156819806/db8f9e3c-f74b-4b68-80a2-803604591789)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

manta network

### Type of the chain

l1/l2

### Link to the page

https://pacific-explorer.manta.network/tx/0xdcb48ec5c7195dd2f613a3ef574ab06ca1bb4ed646bf70c0ede14e2a4cdbec90

### Steps to reproduce

1st : https://manta.layerbank.finance/bank
2nd : https://app.aperture.finance/swap?chainId=169   (i directly choose swap on layerbank website)
3rd : I made my swap ....

### Backend version

1

### Elixir & Erlang/OTP versions

1

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment] 2024-04-04 08:23
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Closed by sl1depengwyn** 2024-04-04 08:23 UTC
Labels: triage

**Comment by sl1depengwyn** [comment] 2024-04-04 08:25
duplicate of https://github.com/orgs/blockscout/discussions/9814
