### ISSUE TITLE
Shahrozshahzad

### ISSUE THREAD

**Issue by Shahrozshahzad** [blockscout/blockscout#10304] opened 2024-06-22 09:27 UTC
### Description

Shahroz

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by GimluCom** [comment] 2024-06-25 11:48
Please clarify exactly what the issue is. Alternatively close this issue if it has been resolved.

**Closed** 2024-07-01 08:06 UTC
Labels: triage
