### ISSUE TITLE
Mumbai: Unauthorized error when writing to contract.

### ISSUE THREAD

**Issue by tobowers** [blockscout/blockscout#3784] opened 2021-04-08 11:54 UTC
When using https://explorer-mumbai.maticvigil.com/address/0xDCb209532108D794e837906eE67317C9ffB61318/write-contract and the addLiquidityMATIC method, I get an "unauthorised" box popping up when I click Write.

![Screen Shot 2021-04-08 at 13 48 17](https://user-images.githubusercontent.com/1274/114021804-62b9c400-9871-11eb-826b-b9082f1f3f27.png)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

### Steps to reproduce

https://explorer-mumbai.maticvigil.com/address/0xDCb209532108D794e837906eE67317C9ffB61318/write-contract

Enter:

9000000000000000000 for minimum ptg
500000000000000000 for value
*validUnixTimestamp* for deadline (eg: 1617892357)

### Expected Behaviour

Meta mask pops up to send the Tx

### Actual Behaviour

Unauthorized error found above.

**Comment by tobowers** [comment] 2021-04-08 13:00
I should say this is kinda a dupe of #3777 but Blockscout has been upgraded there.

**Comment by vbaranov** [comment] 2021-04-20 12:08
Since we have no official support of third-party instances in order to speed up solving of your issue please provide steps on how to reproduce this issue on xDai or Sokol Testnet instance.

**Comment by vbaranov** [comment] 2022-02-09 19:17
This issue should be resolved with Blockscout 4.1.1

**Closed by vbaranov** 2022-02-09 19:17 UTC
Labels: waiting on feedback
