### ISSUE TITLE
ERROR stats_server: service failed with error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Osub** [blockscout/blockscout#8174] opened 2023-08-11 08:29 UTC
```docker logs explorer-stats```
```
2023-08-11T08:21:11.738375Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:12.441994Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:13.160456Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:14.011494Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:15.260489Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:17.360452Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:21.004382Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:27.891754Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
2023-08-11T08:21:41.178480Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
Error: No such file or directory (os error 2)
```

docker-compose.yaml
```
version: '3.8'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: "true"
        RELEASE_VERSION: 5.2.1
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    restart: always
    stop_grace_period: 5m
    container_name: 'explorer-blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000
    volumes:
      - ../../../logs/:/app/logs/

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  stats-db:
    depends_on:
      - blockscout
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - blockscout
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats
```

/services/docker-compose-stats.yml

```
version: '3.8'

services:
  stats-db:
    image: postgres:14
    restart: always
    container_name: 'explorer-stats-postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7433:5432
    volumes:
      - ../../../../stats-db-data:/var/lib/postgresql/data/

  stats:
    depends_on:
      - stats-db
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: 'explorer-stats'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-stats.env
    environment:
      - STATS__DB_URL=postgresql://postgres:@host.docker.internal:7433/stats?ssl=false
      - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true
    ports:
      - 8153:8050
```

**Comment by vbaranov** [comment] 2023-08-11 10:12
@Osub most likely the issue is with this line:
```
    volumes:
      - ../../../../stats-db-data:/var/lib/postgresql/data/
```

I suppose there is no such path `../../../../stats-db-data` on the host machine relatively to /services/docker-compose-stats.yml

**Comment by Osub** [comment] 2023-08-11 13:44
@vbaranov  I get the same error using absolute path, however stats-db uses the same /services/docker-compose-stats.yml, stats-db works fine. But stats reported an error

**Comment by budi760** [comment] 2023-09-29 09:31
getting this too any fix for this?

**Comment by budisetiawan760** [comment] 2023-10-09 04:57
@Osub already fix it with linked the right charts.toml

u should create ur own chart config(u can get default from blockscout-rs repo) and the change config in commont-stats to that file, because seems there is no default config in current built

**Comment by ekawibisono** [comment] 2024-02-16 03:12
> `docker logs explorer-stats`
> 
> ```
> 2023-08-11T08:21:11.738375Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:12.441994Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:13.160456Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:14.011494Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:15.260489Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:17.360452Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:21.004382Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:27.891754Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> 2023-08-11T08:21:41.178480Z ERROR stats_server: service failed with error: No such file or directory (os error 2)
> Error: No such file or directory (os error 2)
> ```
> 
> docker-compose.yaml
> 
> ```
> version: '3.8'
> 
> services:
>   redis_db:
>     extends:
>       file: ./services/docker-compose-redis.yml
>       service: redis_db
> 
>   db:
>     extends:
>       file: ./services/docker-compose-db.yml
>       service: db
> 
>   blockscout:
>     depends_on:
>       - db
>       - smart-contract-verifier
>       - redis_db
>     image: blockscout/blockscout:${DOCKER_TAG:-latest}
>     build:
>       context: ..
>       dockerfile: ./docker/Dockerfile
>       args:
>         CACHE_EXCHANGE_RATES_PERIOD: ""
>         API_V1_READ_METHODS_DISABLED: "false"
>         DISABLE_WEBAPP: "false"
>         API_V1_WRITE_METHODS_DISABLED: "false"
>         CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
>         CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
>         ADMIN_PANEL_ENABLED: "true"
>         RELEASE_VERSION: 5.2.1
>         SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
>     restart: always
>     stop_grace_period: 5m
>     container_name: 'explorer-blockscout'
>     links:
>       - db:database
>     command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
>     extra_hosts:
>       - 'host.docker.internal:host-gateway'
>     env_file:
>       -  ./envs/common-blockscout.env
>     ports:
>       - 4000:4000
>     volumes:
>       - ../../../logs/:/app/logs/
> 
>   smart-contract-verifier:
>     extends:
>       file: ./services/docker-compose-smart-contract-verifier.yml
>       service: smart-contract-verifier
> 
>   visualizer:
>     extends:
>       file: ./services/docker-compose-visualizer.yml
>       service: visualizer
> 
>   sig-provider:
>     extends:
>       file: ./services/docker-compose-sig-provider.yml
>       service: sig-provider
> 
>   stats-db:
>     depends_on:
>       - blockscout
>     extends:
>       file: ./services/docker-compose-stats.yml
>       service: stats-db
> 
>   stats:
>     depends_on:
>       - blockscout
>     extends:
>       file: ./services/docker-compose-stats.yml
>       service: stats
> ```
> 
> /services/docker-compose-stats.yml
> 
> ```
> version: '3.8'
> 
> services:
>   stats-db:
>     image: postgres:14
>     restart: always
>     container_name: 'explorer-stats-postgres'
>     command: postgres -c 'max_connections=200'
>     environment:
>         POSTGRES_PASSWORD: ''
>         POSTGRES_USER: 'postgres'
>         POSTGRES_HOST_AUTH_METHOD: 'trust'
>     ports:
>       - 7433:5432
>     volumes:
>       - ../../../../stats-db-data:/var/lib/postgresql/data/
> 
>   stats:
>     depends_on:
>       - stats-db
>     image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
>     pull_policy: always
>     restart: always
>     container_name: 'explorer-stats'
>     extra_hosts:
>       - 'host.docker.internal:host-gateway'
>     env_file:
>       -  ../envs/common-stats.env
>     environment:
>       - STATS__DB_URL=postgresql://postgres:@host.docker.internal:7433/stats?ssl=false
>       - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
>       - STATS__CREATE_DATABASE=true
>       - STATS__RUN_MIGRATIONS=true
>     ports:
>       - 8153:8050
> ```

hello, you run using os what ? and blockscout version what ?

**Comment by vbaranov** [comment] 2024-05-14 18:59
Closing due to no response from the author.

**Closed by vbaranov** 2024-05-14 18:59 UTC
Labels: waiting on feedback
