### ISSUE TITLE
Smart contract verification issue

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7574] opened 2023-05-29 06:32 UTC
Hi @vbaranov,

Facing issue while verification of smart contract. Gave all the data in input field and then hit verify and publish button it will loading.
Are the data in verification part stored in DB automatically means what is the table name of blockscout db?

how to resolve this error?

Getting this error:
![WhatsApp Image 2023-05-29 at 11 57 09 AM](https://github.com/blockscout/blockscout/assets/81068101/6519f7dd-67c5-4e22-a3c9-1d1d4d0d627a)

**Comment by ekawibisono** [comment] 2023-06-29 02:16
Have you installed smart-contract-verifier? If you use Docker, the smart-contract-verifier will automatically be installed, but you must enter the Secret_Key to verify the contract

**Comment by vbaranov** [comment] 2023-07-26 17:14
Closing due to no answer. Please, provide more details on Blockscout your setup, if the issue is actual.

**Closed by vbaranov** 2023-07-26 17:14 UTC
Labels: waiting on feedback
