### ISSUE TITLE
ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)

### ISSUE THREAD

**Issue by lqucool** [blockscout/blockscout#5934] opened 2022-08-16 09:45 UTC
### Environment

* Operating System: ubuntu20.04
* Blockscout Version/branch: 4.1.7
* postgres: 13.6
* ETH Mainnet (erigon)

Start blockscout in docker with makefile.
```
sudo COIN=ETH \
ETHEREUM_JSONRPC_VARIANT=erigon \
ETHEREUM_JSONRPC_HTTP_URL=http://172.18.0.1:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://172.18.0.1:8545 \
ETHEREUM_JSONRPC_TRACE_URL=http://172.18.0.1:8545 \
BLOCK_TRANSFORMER=base \
NETWORK=Ethereum \
SUBNETWORK=ETH \
DISABLE_KNOWN_TOKENS=true \
INDEXER_MEMORY_LIMIT=12 \
DISABLE_EXCHANGE_RATES=true \
FIRST_BLOCK=10000000 \
LAST_BLOCK=150200000 \
TRACE_FIRST_BLOCK=10000000 \
TRACE_LAST_BLOCK=150200000 \
make start
```

### Problem:
```
2022-08-16T03:26:54.763 [error] Task #PID<0.11798.3> started from Indexer.Fetcher.Token terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (explorer 0.0.1) lib/explorer/chain.ex:4872: anonymous fn/5 in Explorer.Chain.update_token/2
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<140, 56, 101, 169, 161, 151, 67, 202, 20, 38, 135, 193, 82, 63, 63, 106, 163, 204, 11, 227>>}], callback_module: Indexer.Fetcher.Token, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.18.0.1:8545", method_to_url: [eth_getBalance: "http://172.18.0.1:8545", trace_block: "http://172.18.0.1:8545", trace_replayTransaction: "http://172.18.0.1:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Erigon], metadata: []}]
```

Many tasks report this error. Is there any solution?
I can provide more logs if needed.
Thanks.

**Comment by vbaranov** [comment] 2022-08-16 09:47
Duplicate of https://github.com/blockscout/blockscout/issues/5682

**Closed** 2022-09-02 09:46 UTC
Labels: duplicate
