### ISSUE TITLE
GenServer :tzdata_release_updater terminating

### ISSUE THREAD

**Issue by klemenfn** [blockscout/blockscout#10944] opened 2024-10-18 10:19 UTC
### Description

On v6.8.1-beta I see this in error.log after start. Everything seems to work so I don't have further info.

```
2024-10-18T09:49:46.740 [error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update
State: []
```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Steps to reproduce

Unknown

### Backend version

v6.8.1-beta

### Elixir & Erlang/OTP versions

Elixir 1.16.3, Erlang 1.26.52

### Operating system

Ubuntu 22.04

**Comment by GimluCom** [comment] 2024-10-20 14:38
Please share a larger section of the logs along with your ENVs.

**Comment by hhq365** [comment] 2024-11-06 09:15
I have the same issue in backend container:

backend  | {"time":"2024-11-06T09:01:25.790Z","severity":"info","message":"tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.799Z","severity":"info","message":"tx/per day chart: num of transactions 43534","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.837Z","severity":"info","message":"tx/per day chart: total gas used 2327796299","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.879Z","severity":"info","message":"tx/per day chart: total fee 122980702450286","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.879Z","severity":"info","message":"tx/per day chart: collect records for transactions per day stats","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.879Z","severity":"info","message":"tx/per day chart: earliest date 2024-10-31 00:00:00Z","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.879Z","severity":"info","message":"tx/per day chart: latest date 2024-10-31 23:59:59Z","metadata":{}}
backend  | {"time":"2024-11-06T09:01:25.902Z","severity":"info","message":"tx/per day chart: min/max block numbers [8708316, 8751515]","metadata":{}}
backend  | {"time":"2024-11-06T09:01:26.791Z","severity":"error","message":"GenServer :tzdata_release_updater terminating\n** (ArgumentError) errors were found at the given arguments:\n\n  * 2nd argument: not a tuple\n\n    :erlang.element(1, :error)\n    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\nLast message: :check_if_time_to_update\nState: []","metadata":{"error":{"initial_call":null,"reason":"** (ArgumentError) errors were found at the given arguments:\n\n  * 2nd argument: not a tuple\n\n    :erlang.element(1, :error)\n    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\n    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5\n    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1\n"}}}

It's running the latest version (v6.9.0),
Do you hava any idea?

**Comment by vbaranov** [comment] 2024-12-30 21:36
@klemenfn please try currently [latest](https://github.com/blockscout/blockscout/releases/tag/v6.10.0) version of the backend. This issue shouldn't be reproducible there. I am closing this issue for now. Please tell us, if the issue is still present wit the latest release.

**Closed by vbaranov** 2024-12-30 21:36 UTC
Labels: triage
