### ISSUE TITLE
Sourcify: verify contract created from multiple sources

### ISSUE THREAD

**Issue by mfolnovic** [blockscout/blockscout#5686] opened 2022-06-17 16:40 UTC
When trying to verify contract through sourcify, that was created from multiple sources, sourcify asks to choose main contract before continuing. Blockscout should handle this scenario.

### Environment

* Operating System: Linux/Docker
* Blockscout Version/branch: master

### Steps to reproduce

- create and deploy a contract from multiple sources (by importing)
- verify contract via "Sourcify: Sources and metadata JSON file"
- upload json files and submit

### Expected behaviour

Verifying contract (created from multiple sources) through sourcify should work.

### Actual behaviour

![image](https://user-images.githubusercontent.com/20919/174340337-620d024d-efec-4b5d-a586-9e863da16d34.png)

**Comment by nikitosing** [comment] 2022-11-21 18:28
@mfolnovic could you please share contracts code for reproducing this case?

**Comment by vbaranov** [comment] 2023-04-14 14:46
Closing due to no author's response. Please open a new issue, if it is still present.

**Closed by vbaranov** 2023-04-14 14:46 UTC
Labels: contract verification, Sourcify
