### ISSUE TITLE
 error is reported after changing the  _variables.scss 

### ISSUE THREAD

**Issue by avatarvip** [blockscout/blockscout#3770] opened 2021-04-06 09:47 UTC
The error is reported as follows：

The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -' returned a non-zero code: 137
make: *** [build] error 137
![image](https://user-images.githubusercontent.com/66721357/113692347-0aaf8000-9700-11eb-92f6-4c9955c86daa.png)

**Comment by avatarvip** [comment] 2021-04-06 09:47
[
![1617702450227](https://user-images.githubusercontent.com/66721357/113692533-3599d400-9700-11eb-9d9d-eb3c78747b1d.jpg)
](url)

**Comment by vbaranov** [comment] 2021-04-06 09:50
@avatarvip you should ignore this warning. It shouldn't prevent building frontend assets

**Comment by avatarvip** [comment] 2021-04-06 09:55
2 ERRORS in child compilations
webpack 5.8.0 compiled with 4 errors in 444161 ms

asset awesomplete.min.js 7.64 KiB [emitted] [minimized] (name: awesomplete)
asset awesomplete-util.min.js 6.61 KiB [emitted] [minimized] (name: awesomplete-util)
asset ../css/awesomplete.css 1.84 KiB [emitted] (name: awesomplete)
Entrypoint awesomplete 9.48 KiB = ../css/awesomplete.css 1.84 KiB awesomplete.min.js 7.64 KiB
Entrypoint awesomplete-util 6.61 KiB = awesomplete-util.min.js
runtime modules 657 bytes 3 modules
orphan modules 50 bytes [orphan] 1 module
code generated modules 37.7 KiB (javascript) 1.84 KiB (css/mini-extract) [code generated]
  modules by path ./js/lib/*.js 24.9 KiB
    ./js/lib/awesomplete.js 58 bytes [built] [code generated]
    ./js/lib/awesomplete-util.js 24.9 KiB [built] [code generated]
  modules by path ./node_modules/awesomplete/ 12.8 KiB (javascript) 1.84 KiB (css/mini-extract)
    ./node_modules/awesomplete/awesomplete.js 12.8 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/awesomplete/awesomplete.css 1.84 KiB [code generated]
webpack 5.8.0 compiled successfully in 15132 ms
npm ERR! code 1
npm ERR! path /opt/app/apps/block_scout_web/assets
npm ERR! command failed
npm ERR! command sh -c webpack --mode production

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app/.npm/_logs/2021-04-06T09_50_39_065Z-debug.log
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -' returned a non-zero code: 1
make: *** [build] error 1

> you should ignore this warning. It shouldn't prevent building frontend assets

But the build failed

2 ERRORS in child compilations
webpack 5.8.0 compiled with 4 errors in 444161 ms

asset awesomplete.min.js 7.64 KiB [emitted] [minimized] (name: awesomplete)
asset awesomplete-util.min.js 6.61 KiB [emitted] [minimized] (name: awesomplete-util)
asset ../css/awesomplete.css 1.84 KiB [emitted] (name: awesomplete)
Entrypoint awesomplete 9.48 KiB = ../css/awesomplete.css 1.84 KiB awesomplete.min.js 7.64 KiB
Entrypoint awesomplete-util 6.61 KiB = awesomplete-util.min.js
runtime modules 657 bytes 3 modules
orphan modules 50 bytes [orphan] 1 module
code generated modules 37.7 KiB (javascript) 1.84 KiB (css/mini-extract) [code generated]
  modules by path ./js/lib/*.js 24.9 KiB
    ./js/lib/awesomplete.js 58 bytes [built] [code generated]
    ./js/lib/awesomplete-util.js 24.9 KiB [built] [code generated]
  modules by path ./node_modules/awesomplete/ 12.8 KiB (javascript) 1.84 KiB (css/mini-extract)
    ./node_modules/awesomplete/awesomplete.js 12.8 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/awesomplete/awesomplete.css 1.84 KiB [code generated]
webpack 5.8.0 compiled successfully in 15132 ms
npm ERR! code 1
npm ERR! path /opt/app/apps/block_scout_web/assets
npm ERR! command failed
npm ERR! command sh -c webpack --mode production

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app/.npm/_logs/2021-04-06T09_50_39_065Z-debug.log
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -' returned a non-zero code: 1
make: *** [build] error 1

**Comment by avatarvip** [comment] 2021-04-06 09:56
> @avatarvip you should ignore this warning. It shouldn't prevent building frontend assets

![image](https://user-images.githubusercontent.com/66721357/113693609-59114e80-9701-11eb-9bc5-41020934d900.png)

**Comment by vbaranov** [comment] 2021-04-06 10:08
Did you see errors before you changed _variables.scss? Probably, errors caused by changes in that file. Try to create an image with the unmodified file.

**Comment by avatarvip** [comment] 2021-04-06 10:18
> Did you see errors before you changed _variables.scss? Probably, errors caused by changes in that file. Try to create an image with the unmodified file.

The build worked and the browser worked fine before changing _variables.scss, but after changing _variables.scss, it started reporting errors.

**Comment by vbaranov** [comment] 2021-04-06 11:04
>The build worked and the browser worked fine before changing _variables.scss, but after changing _variables.scss, it started reporting errors.

Likely _variables.scss became invalid after the changes. Double-check changes, that you made.

**Comment by avatarvip** [comment] 2021-04-07 06:20
I want to know that all the preset themes in the configuration are available, right?

**Comment by avatarvip** [comment] 2021-04-07 06:40
I want to know that all the preset themes in the configuration are available, right?

**Comment by vbaranov** [comment] 2021-04-20 12:16
I am closing this. Likely, the issue caused by modifications. Please re-open if you unable to compile with default CSS presets.

**Closed by vbaranov** 2021-04-20 12:16 UTC
Labels: waiting on feedback
