### ISSUE TITLE
All methods in read contract tab are duplicated

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#9566] opened 2024-03-06 13:45 UTC
### Description

All read methods seem to be duplicated (starts again at 59). Not sure what other information to share, please advise as needed.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

geth

### Link to the page

https://coston-explorer.flare.network/address/0x6e5A85aB09c2056A9Af46c3Ca5a5A1E6752C8D79/read-contract#address-tabs

### Backend version

v6.1.0-beta

### Elixir & Erlang/OTP versions

v1.14.5 (erlang 25)

### Operating system

Linux

**Comment by vbaranov** [comment] 2024-03-08 15:06
Duplicate of https://github.com/blockscout/blockscout/issues/9175

**Closed** 2024-03-10 15:52 UTC
Labels: duplicate, triage
