### ISSUE TITLE
HTML Decoding issue with token names

### ISSUE THREAD

**Issue by Codj0** [blockscout/blockscout#10901] opened 2024-10-13 11:40 UTC
### Description

The token "Pepe's Balls" is displayed as "Pepe&#39;s Balls".
When displaying the data needs to HTML decoded.
Could be other text fields not just the name.
https://base.blockscout.com/token/0xd16BC23Bb049C82D7704D980607F215D406e08A1

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Base

### Type of the chain

L2

### Link to the page

https://base.blockscout.com/token/0xd16BC23Bb049C82D7704D980607F215D406e08A1

### Backend version

v6.8.1-beta.+commit.ac84cd26

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

-

**Comment by vbaranov** [comment] 2024-12-30 22:55
Duplicate of https://github.com/blockscout/blockscout/issues/10732

**Closed by vbaranov** 2024-12-30 22:55 UTC
Labels: duplicate
