### ISSUE TITLE
Compilers list is empty on Smart Contract verification page

### ISSUE THREAD

**Issue by ifs-medardegue** [blockscout/blockscout#3737] opened 2021-03-24 16:38 UTC
Hello,
I have deployed a container with blockscout docker image in my company. It is connected to a besu node, running a private blockchain. The migration (ecto.create, ecto.migrate) went well, I could start the explorer and search for transaction hash. Everything is running in our corporate network, behind a proxy.

I'm facing different 2 issues for which I don't know if I should create different issues.

1- I want to upload the solidity code for smart contract deployed on my private blockchain (Click on "Verify & Publish" button when you are on a smart contract page). But the compiler drop down is empty. This dropdown list was filled with various solidity compiler versions when I installed and ran blockscout on my MacBook (not the docker image, I cloned the repo and proceeded with the installation guide outside corporate network).

The 2 main differences between the 2 situations are the fact that I now use a docker image in a kubernetes cluster behind a corporate network.

2- Even if the explorer is working as expected, the application keeps logging the following 3 lines indefinitely:
* application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch "URL is nil"
* application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch "URL is nil"
* application=explorer [warn] failed to get known tokens with reason 'nxdomain'.

How can I fix these issues?

### Environment

I'm running the master branch (commit 80cb875) docker image inside a kubernates cluster. I ran docker build on the docker/Dockerfile file and used the resulting image.

**Comment by vbaranov** [comment] 2021-03-26 12:28
@ifs-medardegue  The list of available compiler versions is loaded from the external resource `https://solc-bin.ethereum.org/bin/list.json`. Make sure, that this link is available from your instance.

**Comment by ifs-medardegue** [comment] 2021-03-26 15:57
Thank you for your answer @vbaranov. When I connect to the container and issue a curl, I can reach the url, since I configured the container to run with http_proxy. But it looks like internally, whatever blockscout uses to call the url is not aware of the proxy environment variables.

**Comment by vbaranov** [comment] 2021-03-29 09:57
@ifs-medardegue Did you try to set PORT env variable to the port of your proxy?
Related source: https://phoenixframework.readme.io/docs/serving-your-application-behind-a-proxy

**Comment by ifs-medardegue** [comment] 2021-03-30 11:46
My issue is more related to the fact that blockscout cannot connect to internet. This link is helpful in case we want blockscout to handle requests sent to it through our proxy. We don't plan to serve blockscout oustside our dev environment. i'm currently working on a workaround to serve the solidity compilers from a static file server inside out cluster. I would then need to update the url in blockscout code before compile time.

**Comment by vbaranov** [comment] 2021-03-30 12:27
@ifs-medardegue Ok, understood. I suppose this issue should be fixed by implementing customizations to your instance rather than updating a Blockscout core because Blockscout by design has fetchers that depend on 3d party providers. Apart from the list of Solc compiler versions,
1. You should also disable exchange rates fetching which is powered by CoinGecko API. In order to disable it, set `export DISABLE_EXCHANGE_RATES=true`.

> Disables or enables fetching of coin price from Coingecko API

Source: https://docs.blockscout.com/for-developers/information-and-settings/env-variables

2. Contracts verification will not in an operational state until you have all compilers at `./apps/explorers/priv/solc_compilers`. In the core version of Blockscout requested compiler is downloaded to this location from `https://solc-bin.ethereum.org/bin/soljson-#{version}.js`


Take a note also, that ERC-721 media files will not be served from the external links. Blockscout doesn't fetch those media files to the DB in order to prevent bloating of DB.

**Closed by vbaranov** 2021-03-30 12:27 UTC
Labels: waiting on feedback
