### ISSUE TITLE
Costume Theme Cannot Change

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6490] opened 2022-11-22 06:10 UTC
im trying to change UI theme in blockscout neutral_var to ether_var but UI cannot change

### Environment
* Deployment type (Docker-compose): latest
* Operating System: Ubuntu
* Blockscout Version/branch/commit: v4.1.3

### Expected behaviour

![image](https://user-images.githubusercontent.com/93043826/203237909-257f8de7-d76f-4992-9254-d972c8c3c701.png)

**Comment by avenbreaks** [comment] 2022-11-22 06:38
Im running using docker sir, position blockscout running and i try to command : docker-compose up -d

**Comment by vbaranov** [comment] 2022-11-22 06:53
Then you need to rebuild the image: `docker-compose up --build`

**Comment by vbaranov** [comment] 2022-11-23 20:53
I am closing this. Please re-open, if the issue is still present.

**Closed by vbaranov** 2022-11-23 20:53 UTC
Labels: waiting on feedback
