### ISSUE TITLE
docker-compose: fails to pull smart-contract-verifier

### ISSUE THREAD

**Issue by PierrickGT** [blockscout/blockscout#7440] opened 2023-05-09 15:44 UTC
I'm trying to run blockscout locally using Docker but when I run `docker-compose up --build`, I get the following error:
```
Pulling smart-contract-verifier (ghcr.io/blockscout/smart-contract-verifier:main)...
ERROR: Head "https://ghcr.io/v2/blockscout/smart-contract-verifier/manifests/main": denied: denied
```

It also looks like the doc has not been updated: https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only
Informations differ from the one in the README: https://github.com/blockscout/blockscout/tree/master/docker-compose

### Steps to reproduce

Run `docker-compose up --build` in the `docker-compose` folder.

**Comment by vbaranov** [comment] 2023-05-10 11:02
@PierrickGT I couldn't reproduce the unavailability of the main tag. However, changed it to the `latest` tag just in case. Please pull the update from the master branch and let me know if the issue still exists. And updated both guides: in readme and docs. Thanks for the heads-up.

**Comment by PierrickGT** [comment] 2023-05-10 15:51
> https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only

Thanks for the help.
I'm now able to pull after running `docker logout ghcr.io`, I was using an expired access token and that's why it failed to pull.

Now I'm encountering the following issue: `ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`
So I guess the image does not run on ARM64 architectures?

**Comment by wzglgo** [comment] 2023-05-17 02:47
This might be a problem with ghcr.io, just wait a little longer. I have encountered it too, I waited for about 20 minutes before the pull was successful

**Comment by vbaranov** [comment] 2023-07-26 12:59
> > https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only
> 
> Thanks for the help. I'm now able to pull after running `docker logout ghcr.io`, I was using an expired access token and that's why it failed to pull.
> 
> Now I'm encountering the following issue: `ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries` So I guess the image does not run on ARM64 architectures?

Docker image with master tag should work on ARM architecture. Please let me know, if this is not. I am closing this for now.

**Closed by vbaranov** 2023-07-26 12:59 UTC
Labels: waiting on feedback
