### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by OsKooRa** [blockscout/blockscout#4957] opened 2021-11-29 12:11 UTC
![لقطة الشاشة 2021-11-29 150331](https://user-images.githubusercontent.com/95223327/143865546-52c2c337-86da-4fe8-88be-3a84649897d2.png)
*Describe your issue here.*
My money is PENDING from three days, why?
### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment] 2021-11-29 13:02
Duplicate of https://github.com/blockscout/blockscout/issues/4956

**Closed** 2021-11-29 13:27 UTC
