### ISSUE TITLE
coin I swapped is not in my wallet

### ISSUE THREAD

**Issue by fozruk0** [blockscout/blockscout#9768] opened 2024-04-01 00:02 UTC
### Description

I exchanged my degen coins with SAITAMA, txn is below;

https://explorer.degen.tips/tx/0x538b5cf45a80a13efd5652f1a187b8ae7961340c59d9808eed7aec5fa4548f46

This is my 5th from last transaction. I should have 99 SAITAMAs in my wallet but I don't.

Afterwards, there is no action to remove my SAITAMAs from the wallet, so why are there no SAITAMAs in my wallet? can you help me

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

degen

### Link to the page

https://explorer.degen.tips/address/0xeC5dCB35938E6BB62c0C956F05e13b4Bd70761c2

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

degen

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by GimluCom** [comment] 2024-04-02 00:43
Your issue has nothing to do with Blockscout, however this is likely the culprit of your issue: https://github.com/blockscout/blockscout/issues/9766#issuecomment-2030858500

Duplicate of #9766

**Closed** 2024-04-03 08:58 UTC
Labels: triage
