### ISSUE TITLE
Ganache & Blockscout with docker-compose: http://host.docker.internal:8545/ is unavailable.

### ISSUE THREAD

**Issue by cryptotester** [blockscout/blockscout#5951] opened 2022-08-18 17:05 UTC
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): taken via docker
* Operating System: Linux Fedora 36
* latest version of blockscout (`git clone https://github.com/blockscout/blockscout` 2022-08-18)
* Docker version 20.10.17, build 100c701
* docker-compose version 1.29.2

### Steps to reproduce

I'm trying to configure blockscout to be used locally with ganache.

I have ganache v7.4.1 installed via `sudo yarn global add ganache`

I run ganache like this, I provide a mnemonic to persist the setup, also "ganache_1" is the folder where the ganache db is saved (in my home)

```
ganache-cli --db ganache_1 --accounts 20 --mnemonic="my mnemonic"
```

I get:
```
[...]
Chain Id
==================
1337

RPC Listening on 127.0.0.1:8545
```

I tried also to provide as host localhost, like this:

```
ganache-cli --db ganache_1 --accounts 20 --mnemonic="my mnemonic" -h localhost
```

I get:
```
[...]
Chain Id
==================
1337

RPC Listening on localhost:8545
```

In MetaMask in both cases I can connect and see my ganache wallet balances, the default coin is  `CPAY`.

I can deploy smart contracts to this specific ganache instance, via truffle, and it works. So my ganache instance... works.

Now the blockscout part. As said I did clone the blockscout repo, then followed this guide:
https://github.com/blockscout/blockscout/blob/master/docker-compose/README.md

I did run

```
docker-compose up --build
```

When ready I pressed `Ctrl+C` to stop it (and also `docker-composer down`, in order to run the config for ganache, as follows:

```
docker-compose -f docker-compose-no-build-ganache.yml up
```
(I do not provide the `-d` option, not to detach, to see what happens... in the logs I see:

![image](https://user-images.githubusercontent.com/49552918/185452190-c7c5ce57-ac22-4047-9e81-4f9b73b72cb7.png)

Lots of errors like this one:

```
2022-08-18T16:54:31.493 application=indexer fetcher=block_catchup [error] Catchup index stream exited because the archive node endpoint at http://host.docker.internal:8545/ is unavailable. Restarting
```

I'm not a docker expert, also normally when there is a docker file etc. I expect it to work, anyway I think there is a communication issue between docker and my ganache instance running on port 8545. Apparently blockscout cannot reach it.

I checked e.g. https://forums.docker.com/t/how-to-reach-localhost-on-host-from-docker-container/113321/5

I tried to edit the `docker-compose-no-build-ganache.yml` and replace the host in these lines (line 30 and 31:

```
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
```

Instead of `host.docker.internal` I tried `172.17.0.1` and `172.18.0.1`. I didn't build again, I tried in both cases just to run `docker-compose -f docker-compose-no-build-ganache.yml up`

I didn't touch the file `./envs/common-blockscout.env`

Same issue. Hope you can help ke to make this work.

Thanks in advance & cheers

### Expected behaviour

Browsing to http://localhost:4000/ should work. I should be able to see my local ganache blockchain blocks, transactions etc.

### Actual behaviour

I try to browse to http://localhost:4000/
It doesn't work (site can't be reached)

**Comment by cryptotester** [comment] 2022-08-19 12:39
> @cryptotester which version of Docker is installed? It should be 20.x+
> 
> I just run `DOCKER_TAG=4.1.7 docker-compose -f docker-compose-no-build-ganache.yml up` and latest ganache on the same machine. And the explorer started without issues.

Hi, thanks for the reply. I updated the original question and included the info:
* Docker version 20.10.17, build 100c701
* docker-compose version 1.29.2

Did you also try on Linux? How did you run ganache, like the command in my report or differently?

I tried to run (inside the github `docker-compose` directory) the command you shared `DOCKER_TAG=4.1.7 docker-compose -f docker-compose-no-build-ganache.yml up` (that's how it is supposed to run? sorry if i missed something, as said i'm not a docker expert i use docker in a basic way). Same issue:

```
2022-08-19T12:37:32.713 application=indexer fetcher=block_catchup [error] Catchup index stream exited because the archive node endpoint at http://host.docker.internal:8545/ is unavailable. Restarting
```

**Comment by vbaranov** [comment] 2022-08-31 19:13
@cryptotester the issue is with how you've launched ganache. You should remove `-h localhost`. Thus, the command to run Ganache should be: `ganache-cli --db ganache_1 --accounts 20 --mnemonic="my mnemonic"`

**Comment by vbaranov** [comment] 2022-09-01 20:00
I am closing this issue. Please let me know, if the issue didn't resolve on your end.

**Closed by vbaranov** 2022-09-01 20:00 UTC
Labels: waiting on feedback

**Comment by cryptotester** [comment] 2022-09-13 13:06
@vbaranov I tried as you said, removing -h localhost. It was not that. Same issue `Catchup index stream exited because the archive node endpoint at http://host.docker.internal:8545/ is unavailable. Restarting`

If it just works so easily on your end, do you mind making a little step by step guide on linux, or copy/paste the various commands you run and from where you run them, and let me know if you also use Linux?

Because I read somewhere that `host.docker.internal` is for Windows.

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

If you just tell me you are using Windows, it would make sense that everything works fine for you.

Thx for letting me know

**Comment by dbale-altoros** [comment] 2022-11-01 20:21
@cryptotester 
I ran it with hardhat instead of ganache
for linux you should execute docker ps and see in the ports what is the ip address
if its 0.0.0.0 you should run your ganache instance in that ip
leave the env as they are
maybe increase the ACCOUNT_POOL_SIZE but that's it 
it should work
