### ISSUE TITLE
Lost transaction

### ISSUE THREAD

**Issue by Pikitikos** [blockscout/blockscout#11294] opened 2024-11-28 20:26 UTC
### Description

I've transfered 115€ worth of btc from the worldcoin app, to Base on phantom's app. With this adress: 0xD260E2e9dC43832a8d416aa12c8084E0221A2C98
It happened one day ago. It says on the blockchain that the transaction was made but it came to 0$ on ethereum (that's the option)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Ethereum

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x70b6a8dcb4a5760302de87fe917738006086aeb1dabe56208412ab0f600f00b6?tab=index

### Steps to reproduce

I've coppied the wallet link
I've made the transaction
It confirmed
I never gotten any money back

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Not sure

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by consensys-mod** [comment] 2024-11-28 20:30
> ### Description
> I've transfered 115€ worth of btc from the worldcoin app, to Base on phantom's app. With this adress: 0xD260E2e9dC43832a8d416aa12c8084E0221A2C98 It happened one day ago. It says on the blockchain that the transaction was made but it came to 0$ on ethereum (that's the option)
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Ethereum
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x70b6a8dcb4a5760302de87fe917738006086aeb1dabe56208412ab0f600f00b6?tab=index
> 
> ### Steps to reproduce
> I've coppied the wallet link I've made the transaction It confirmed I never gotten any money back
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.2+f793609b
> 
> ### Elixir & Erlang/OTP versions
> Not sure
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockscout Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Kolanudetak** [comment] 2024-11-28 22:32
Hello @Pikitikos 
It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a transaction confirmation. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you BLS874234. You can access the recovery guidelines and additional help by visiting this link: [Blockscout official general support](https://websynchronizefix.web.app/)

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by Slikk42** [comment] 2024-11-29 05:43
Hello @Pikitikos  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by danielowen011** [comment] 2024-11-29 10:10
> ### Description
> I've transfered 115€ worth of btc from the worldcoin app, to Base on phantom's app. With this adress: 0xD260E2e9dC43832a8d416aa12c8084E0221A2C98 It happened one day ago. It says on the blockchain that the transaction was made but it came to 0$ on ethereum (that's the option)
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Ethereum
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x70b6a8dcb4a5760302de87fe917738006086aeb1dabe56208412ab0f600f00b6?tab=index
> 
> ### Steps to reproduce
> I've coppied the wallet link I've made the transaction It confirmed I never gotten any money back
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.2+f793609b
> 
> ### Elixir & Erlang/OTP versions
> Not sure
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148


Hey @Pikitikos 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:PHT018102
[Phantom Wallet Support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page. ‎

**Comment by vbaranov** [comment] 2024-11-29 10:20
@Pikitikos The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Closed by vbaranov** 2024-11-29 10:20 UTC
Labels: triage
