### ISSUE TITLE
Ethereum Classic: Missing blocks, transactions

### ISSUE THREAD

**Issue by TheTrunk** [blockscout/blockscout#4634] opened 2021-09-11 08:04 UTC
Following address does not show all transactions: 0xcb63642a22E4F07748329aF51D882612E1d51E27
After looking further into issue, some blocks are not processed correctly.
For example https://blockscout.com/etc/mainnet/blocks/13505874/transactions and many others are impossible to view.
Roughly last 3-4 days is processed wrongly

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36`

### Steps to reproduce

Some blocks and transactions from last 3-4 days are missing
https://blockscout.com/etc/mainnet/blocks/13505874/transactions

### Expected Behaviour

Blocks, transactions exists, addresses are updated

### Actual Behaviour

Blcoks are missing, were not processed

**Comment by vbaranov** [comment] 2021-09-13 08:52
This is a duplicate of #4627

**Comment by vbaranov** [comment] 2021-09-14 11:49
The issue with indexing was resolved.

**Closed by vbaranov** 2021-09-14 11:49 UTC
Labels: duplicate, chain: ETC :chains:
