### ISSUE TITLE
Can't be deployed by docker-compose: Failed to load common-smart-contract-verifier.env

### ISSUE THREAD

**Issue by lity** [blockscout/blockscout#6909] opened 2023-02-16 05:48 UTC
I cloned the project(https://github.com/blockscout/blockscout/tree/e8e52edb47f2ab9884d9383127c736ceb0e21c93) and tried to start blockscout by command "docker compose -f ./docker-compose-no-build-hardhat-network.yml up -d", but got such error:

Failed to load /home/lty/blockscout/envs/common-smart-contract-verifier.env: open /home/lty/blockscout/envs/common-smart-contract-verifier.env: no such file or directory

### Environment

Windows11 WSL2 Ubuntu 22.04.1 LTS
Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.16.0

### Steps to reproduce

1. Clone the project (https://github.com/blockscout/blockscout/tree/e8e52edb47f2ab9884d9383127c736ceb0e21c93)
2. cd blockscout/docker-compose/ 
3. Run command: "docker compose -f ./docker-compose-no-build-hardhat-network.yml up -d"

### Expected behaviour

blockscout start 

### Actual behaviour

docker compose report error.

**Comment by lity** [comment] 2023-02-16 05:53
I found a similar issue, https://github.com/blockscout/blockscout/issues/6862.

It's probably caused by docker compose version.

**Comment by martianacademy** [comment] 2023-02-16 08:15
its a version problem. install docker-compose version 1.29.2, build 5becea4c version problem will gone.

**Comment by martianacademy** [comment] 2023-02-16 08:18
process:

sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

docker-compose --version

docker-compose version 1.29.2, build 5becea4c

then switch to blockscout/docker-compose & run docker-compose up --build

this will build the image and run the containers.

if you want to start in detached mode 

just do:

docker-compose up -a --build

**Comment by lity** [comment] 2023-02-16 09:13
> 

Thanks for your solution. Docker Compose V1 is outdated, I hope the latest version of Docker Compose could work with blockscout.

**Comment by vbaranov** [comment] 2023-02-16 10:06
I am closing this issue. @lity let me know, if the issue is still present.

**Closed by vbaranov** 2023-02-16 10:06 UTC
