### ISSUE TITLE
Chart and stats issue

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#9636] opened 2024-03-14 10:33 UTC
### Description

Hi,
Running blockscout with docker-compose. In frontend, charts and stats page data are not shown.
Can i add any URL in env file?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Backend version

v6.1.0

### Frontend version

latest

### Elixir & Erlang/OTP versions

latest

**Comment by sl1depengwyn** [comment] 2024-03-15 14:34
Duplicate of https://github.com/orgs/blockscout/discussions/9634

**Closed by sl1depengwyn** 2024-03-15 14:34 UTC
Labels: triage
