### ISSUE TITLE
BlockScoutWeb.Counters.InternalTransactionsIndexedCounter terminating

### ISSUE THREAD

**Issue by ganzr** [blockscout/blockscout#8927] opened 2023-12-04 02:20 UTC
### Description

After running for about one day, blockscout_web stops working, and it will be 504 gateway timeout error shown by chrome browser. 
There are some errors like below:
2023-12-04T02:15:32.379 [error] Task #PID<0.1631.6080> started from BlockScoutWeb.Counters.InternalTransactionsIndexedCounter terminating
** (stop) exited in: GenServer.call(#PID<0.32151.6016>, {:lock, :async_task, #Reference<0.3096470770.868483078.112795>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.1) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (explorer 5.3.1) lib/explorer/chain/cache/pending_block_operation.ex:6: Explorer.Chain.Cache.PendingBlockOperation.get/1
    (explorer 5.3.1) lib/explorer/chain/cache/pending_block_operation.ex:40: Explorer.Chain.Cache.PendingBlockOperation.handle_fallback/1
    (explorer 5.3.1) lib/explorer/chain/cache/pending_block_operation.ex:6: Explorer.Chain.Cache.PendingBlockOperation.get/1
    (explorer 5.3.1) lib/explorer/chain/cache/pending_block_operation.ex:26: Explorer.Chain.Cache.PendingBlockOperation.estimated_count/0
    (explorer 5.3.1) lib/explorer/chain.ex:1827: Explorer.Chain.indexed_ratio_internal_transactions/0
    (block_scout_web 5.3.1) lib/block_scout_web/counters/internal_transactions_indexed_counter.ex:39: BlockScoutWeb.Counters.InternalTransactionsIndexedCounter.calculate_internal_transactions_indexed/0
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.122797066/0 in BlockScoutWeb.Counters.InternalTransactionsIndexedCounter.calculate_internal_transactions_indexed>
    Args: []
2023-12-04T02:15:32.380 [error] Task #PID<0.590.6080> started from #PID<0.1631.6080> terminating
** (stop) exited in: GenServer.call(#PID<0.31824.6016>, {:lock, :count, #Reference<0.3096470770.766509064.176602>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.1) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (explorer 5.3.1) lib/explorer/chain/cache/pending_block_operation.ex:53: anonymous fn/0 in Explorer.Chain.Cache.PendingBlockOperation.handle_fallback/1
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.102967692/0 in Explorer.Chain.Cache.PendingBlockOperation.handle_fallback/1>
    Args: [] 
2023-12-04T02:15:34.099 [error] Task #PID<0.2203.6080> started from BlockScoutWeb.Counters.BlocksIndexedCounter terminating
** (stop) exited in: GenServer.call(#PID<0.5211.6017>, {:lock, :async_task, #Reference<0.3096470770.1026818050.62408>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.1) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (explorer 5.3.1) lib/explorer/chain/cache/block.ex:11: Explorer.Chain.Cache.Block.get/1
    (explorer 5.3.1) lib/explorer/chain/cache/block.ex:57: Explorer.Chain.Cache.Block.handle_fallback/1
    (explorer 5.3.1) lib/explorer/chain/cache/block.ex:11: Explorer.Chain.Cache.Block.get/1
    (explorer 5.3.1) lib/explorer/chain/cache/block.ex:34: Explorer.Chain.Cache.Block.estimated_count/0
    (explorer 5.3.1) lib/explorer/chain.ex:1806: Explorer.Chain.indexed_ratio_blocks/0
    (block_scout_web 5.3.1) lib/block_scout_web/counters/blocks_indexed_counter.ex:39: BlockScoutWeb.Counters.BlocksIndexedCounter.calculate_blocks_indexed_and_broadcast/0
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.126841135/0 in BlockScoutWeb.Counters.BlocksIndexedCounter.calculate_blocks_indexed_and_broadcast>
    Args: []

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Additional information

ENV is as below:
export MIX_ENV=dev
export INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=false
export MICROSERVICE_SC_VERIFIER_ENABLED=true
export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/
export POOL_SIZE=200
export PORT=3030
export NETWORK=
export BLOCKSCOUT_VERSION=5.3.1
export SOURCIFY_INTEGRATION_ENABLED=false
export INDEXER_MEMORY_LIMIT=8368709120
export INDEXER_HIDE_INDEXING_PROGRESS_ALERT=true
export DISABLE_EXCHANGE_RATES=true
export CACHE_BLOCK_COUNT_PERIOD=1h
export CACHE_PBO_COUNT_PERIOD=10m

**Comment by ganzr** [comment] 2023-12-05 05:19
Is this problem related to the sc verifyer service?
I have succeeded to verify my smart contract on the website.
Anyway, I would like to give a try. Thanks a lot~

**Comment by ekawibisono** [comment] 2023-12-05 07:27
hi @ganzr 
If you're running smartcontract on its own that's fine, I'm just providing a new version of smartcontract.

Note : If the problem is solved, please close the issue. thanks

**Comment by ganzr** [comment] 2023-12-07 02:53
@ekawibisono 
The issus is still there. And I have monitored the resource usage as below.
<img width="1440" alt="image" src="https://github.com/blockscout/blockscout/assets/20966436/df26897c-5c68-41ad-acac-3806005cebff">
It seems that at 8:00 CPU usage cuts down to 0%. And the website has no response just as below.
<img width="1342" alt="image" src="https://github.com/blockscout/blockscout/assets/20966436/df8144cc-e060-40ee-970d-1399f917b104">

**Comment by ganzr** [comment] 2023-12-07 06:27
I've collected the logs when this issus happens. And I've found that every time the issue happens, the error as below will show up in the first place, and CPU usage will decrease to 0%, other error will keep showing up.
2023-12-07T05:10:25.766 [error] GenServer #PID<0.1328.0> terminating
** (stop) exited in: GenServer.call(#PID<0.1324.0>, {:lock, :old_gas_prices, #Reference<0.1882616394.2068316165.214415>}, 5000)
    ** (EXIT) time out
    (elixir 1.14.1) lib/gen_server.ex:1038: GenServer.call/3
    (con_cache 1.0.0) lib/con_cache/lock.ex:22: ConCache.Lock.exec/4
    (con_cache 1.0.0) lib/con_cache/owner.ex:218: anonymous fn/3 in ConCache.Owner.purge/1
    (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (con_cache 1.0.0) lib/con_cache/owner.ex:217: ConCache.Owner.purge/1
    (con_cache 1.0.0) lib/con_cache/owner.ex:65: ConCache.Owner.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :check_purge
State: %ConCache.Owner{ttl_check: 1000, current_time: 7853, pending: #Reference<0.1882616394.2034368516.88733>, ttls: #Reference<0.1882616394.2034368516.88734>, max_time: 65535, on_expire: #Function<6.17635817/1 in ConCache.Owner.start_ttl_loop/1>}

**Comment by ganzr** [comment] 2023-12-07 06:28
BTW, the time speed of committing a block in my case is about 1 block/second

**Comment by ganzr** [comment] 2023-12-21 02:36
It seems that this issue is related to the ecto or account, because when i set the level from 'debug' to 'info', this issue is gone.
<img width="1512" alt="image" src="https://github.com/blockscout/blockscout/assets/20966436/c401e02b-dc42-4818-833d-6dc67992d5b0">

**Closed** 2023-12-28 12:19 UTC
Labels: triage
