### ISSUE TITLE
# qemu: uncaught target signal 11 (Segmentation fault) - core dumped  

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6927] opened 2023-02-17 16:45 UTC
*Describe your issue here.*

getting the error attached.

OS: MacOS, M2Pro Chip
<img width="1728" alt="Screenshot 2023-02-17 at 10 13 18 PM" src="https://user-images.githubusercontent.com/110845434/219713607-1e9106c8-14e3-4184-aa33-08a3773a2b4b.png">

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
[](url)
<img width="1728" alt="Screenshot 2023-02-17 at 10 13 18 PM" src="https://user-images.githubusercontent.com/110845434/219713463-d331017a-352f-4270-9055-f3566209772a.png">

**Comment by vbaranov** [comment] 2023-02-17 17:10
Duplicate of https://github.com/blockscout/blockscout/issues/6787

**Closed** 2023-07-26 11:23 UTC
Labels: duplicate
