### ISSUE TITLE
No tokens found, when wallet has tokens

### ISSUE THREAD

**Issue by ninode97** [blockscout/blockscout#6775] opened 2023-01-26 23:38 UTC
I was building an application that uses [](https://blockscout.com/eth/mainnet/api-docs)

and calculates balance of provided wallets. 

It was working fine like in December and now the API returns "No tokens found".

When checking the same wallet with Etherscan, it shows the tokens (they are still there) but it seems the BlockScout fails to list them.

### Environment
Using hosted version of blockscout (official website).

### Steps to reproduce
1. Navigate to the official website - https://blockscout.com/eth/mainnet/api-docs
2. Test endpoint `?module=account&action=tokenlist&address={addressHash}`
3. Provide wallet id `0xa3cdc8F549CBE48248E11926578e76D3DCd16b3E`
4. No tokens found.

5. Checking on etherscan:
https://etherscan.io/address/0xa3cdc8F549CBE48248E11926578e76D3DCd16b3E

### Expected behaviour

1. Provide address hash to blockscout API endpoint '?module=account&action=tokenlist&address={addressHash}`'
2. Retrieve the tokens that are available within the wallet.

### Actual behaviour

1. Provide address hash to blockscout API endpoint '?module=account&action=tokenlist&address={addressHash}`'
2. Returns empty token list.

### Additional Notes
Sorry if I am missing anything, but just thinking by any chance someone might now what I am doing wrong?

**Comment by harveyff** [comment] 2023-02-03 03:59
I think the team reset the data for https://blockscout.com/eth/mainnet, currently it is restarting the sync, the progress is less than 1%, I don't know why this happened

**Comment by ninode97** [comment] 2023-02-05 19:29
Is there any information about sync progress when it will finish syncing?

**Comment by vbaranov** [comment] 2023-08-21 20:34
@ninode97 I can see tokens on the address `0xa3cdc8F549CBE48248E11926578e76D3DCd16b3E` now in Blockscout. I am closing this issue. Please, let me know, if you still observe, that the issue is present.

**Closed by vbaranov** 2023-08-21 20:34 UTC
Labels: chain: ETH :chains:
