### ISSUE TITLE
GraphQL Scheme is not working.

### ISSUE THREAD

**Issue by Ivanbruce2** [blockscout/blockscout#9765] opened 2024-03-31 16:07 UTC
### Description

I noted that the doc segement for graphQL is not working. There is an error message.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BASE

### Type of the chain

L2

### Link to the page

https://base.blockscout.com/graphiql

### Backend version

v6.3.0-beta.+commit.deb5dce4

### Frontend version

v1.27.0+5a63649f

### Elixir & Erlang/OTP versions

Nil

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment] 2024-04-03 08:54
duplicate of https://github.com/blockscout/blockscout/issues/9135

**Closed by sl1depengwyn** 2024-04-03 08:54 UTC
Labels: triage
