### ISSUE TITLE
Email verification issue ?

### ISSUE THREAD

**Issue by Gopal-Gurram** [blockscout/blockscout#8433] opened 2023-09-11 05:04 UTC
After a 5m interval I click the resent email link but get the below error. 👇

![image](https://github.com/blockscout/blockscout/assets/59303056/daf8a1f0-e204-4106-b8a0-425c7f262bdb)

**Comment by Gopal-Gurram** [comment] 2023-09-13 04:53
@vbaranov Do we need SendGrid env variables to send a verification email?

**Comment by sl1depengwyn** [comment] 2023-09-18 10:04
> @vbaranov Do we need SendGrid env variables to send a verification email?

Yes

**Comment by vbaranov** [comment] 2024-05-14 18:55
> @vbaranov Do we need SendGrid env variables to send a verification email?

No, SendGrid is not required for verification email - it is sent by Auth0. Make sure Redis is working and Blockscout connected to it and you configured [account-related env vars](https://docs.blockscout.com/for-developers/configuration-options/my-account-settings) properly. I am closing this ticket. Please let us know, if the issue is still present and provide more details on your account setup, if so.

**Closed by vbaranov** 2024-05-14 18:55 UTC
Labels: Account
