### ISSUE TITLE
fail with code 404 when request to token uri/token_instances

### ISSUE THREAD

**Issue by BlockgenStudio** [blockscout/blockscout#9603] opened 2024-03-11 15:55 UTC
### Description

I am trying to deploy block scout for a polygon edge private appchian

we get the following error:
`backend          | {"time":"2024-03-11T14:58:07.453Z","severity":"warn","message":"Request to token uri: \"https://cert.client.org/xxxxxxxxxxxx\" failed with code 404. Body:\"\"","metadata":{"fetcher":"token_instances"}}
`
any idea what went wrong and how to fix this?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Steps to reproduce

```
Checkout git@github.com:blockscout/blockscout.git
cd docker-compose
edit envs/common-blockscout.env:
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=our polygon-edge json-rpc endpoint
ETHEREUM_JSONRPC_TRACE_URL=our polygon-edge json-rpc endpoint
JSON_RPC=our polygon-edge json-rpc endpoint
CHAIN_ID=our chain id
DATABASE_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE=polygon_edge
4. run docker-compose -f ./geth.yml up

```

### Backend version

v6.2

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

macOS

**Comment by sl1depengwyn** [comment] 2024-03-11 23:36
Duplicate of https://github.com/orgs/blockscout/discussions/9602

**Closed by sl1depengwyn** 2024-03-11 23:36 UTC
Labels: triage
