### ISSUE TITLE
(-32602) invalid argument 0: hex string has length 0, want 40 for common.Address

### ISSUE THREAD

**Issue by SurenFTN** [blockscout/blockscout#8280] opened 2023-08-23 11:16 UTC
### Environment
Hey there I have an issue  concerning read and interacting with Smart Contract after its verification. https://sahara.ftnscan.com/address/0x385C32d00cD8FF896eCd7Ca3335bb30f391a3057/read-contract#address-tabs
I am getting error on this two functions which are View and not receiving any args get_deposit_count(), get_deposit_root() 

(-32602) invalid argument 0: hex string has length 0, want 40 for common.Address

**Comment by vbaranov** [comment] 2023-08-23 11:56
@SurenFTN which version of Blockscout do you use for this chain? We cannot reproduce with the latest 5.2.2 release.

**Comment by SurenFTN** [comment] 2023-08-24 13:41
`# ChangeLog

## Current

### Features

- [#6721](https://github.com/blockscout/blockscout/pull/6721) - Implement fetching internal transactions from callTracer
- [#6712](https://github.com/blockscout/blockscout/pull/6712) - API v2 update

### Fixes

- [#6746](https://github.com/blockscout/blockscout/pull/6746) - Fix -1 address counter
- [#6736](https://github.com/blockscout/blockscout/pull/6736) - Fix `/tokens` in old UI
- [#6705](https://github.com/blockscout/blockscout/pull/6705) - Fix `/smart-contracts` bugs in API v2
- [#6740](https://github.com/blockscout/blockscout/pull/6740) - Fix tokens deadlock
- [#6759](https://github.com/blockscout/blockscout/pull/6759) - Add `jq` in docker image

### Chore

- [#6695](https://github.com/blockscout/blockscout/pull/6695) - Process errors and warnings with enables check-js feature in VS code

<details>
  <summary>Dependencies version bumps</summary>
</details>

## 5.0.0-beta
`

**Comment by SurenFTN** [comment] 2023-08-24 13:41
I believe it is 5.0.0

**Comment by vbaranov** [comment] 2023-08-24 13:43
@SurenFTN it is quite old. Could you update to 5.2.2?

**Comment by SurenFTN** [comment] 2023-08-24 13:44
:)  is there any possibilty to you have your direct contact any messenger is acceptable

**Comment by SurenFTN** [comment] 2023-08-24 14:20
Thank you so much !

**Comment by vbaranov** [comment] 2023-09-28 13:54
I am closing this. Please let us know, if the issue still present with the latest version of Blockscout.

**Closed by vbaranov** 2023-09-28 13:54 UTC
Labels: waiting on feedback
