### ISSUE TITLE
user-ops-indexer not work

### ISSUE THREAD

**Issue by supertobby** [blockscout/blockscout#10182] opened 2024-06-03 06:06 UTC
##  service of user-ops-indexer not work , logs as:
`user-ops-indexer  | 2024-06-03T05:58:15.520234Z  INFO sqlx::postgres::notice: relation "user_ops_indexer_migrations" already exists, skipping
user-ops-indexer  | 2024-06-03T05:58:15.520262Z  INFO sea_orm_migration::migrator: Applying all pending migrations
user-ops-indexer  | 2024-06-03T05:58:15.520374Z  INFO sqlx::postgres::notice: relation "user_ops_indexer_migrations" already exists, skipping
user-ops-indexer  | 2024-06-03T05:58:15.520455Z  INFO sqlx::postgres::notice: relation "user_ops_indexer_migrations" already exists, skipping
user-ops-indexer  | 2024-06-03T05:58:15.520546Z  INFO sqlx::postgres::notice: relation "user_ops_indexer_migrations" already exists, skipping
user-ops-indexer  | 2024-06-03T05:58:15.521270Z  INFO sea_orm_migration::migrator: No pending migrations
user-ops-indexer  | 2024-06-03T05:58:15.521405Z  INFO user_ops_indexer_server::indexer: connecting to rpc version="v0.6"
user-ops-indexer  | Error: HTTP error: 405 Method Not Allowed`
in envs/common-user-ops-indexer.env
I set:
`USER_OPS_INDEXER__INDEXER__RPC_URL="http://10.40.112.7:8545"`
I don't know where is wrong ,or should I just stop service user-ops-indexer?I noticed that this service is not in docker compose serveral weeks ago.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

cosmos node

### Type of the chain

l1

### Backend version

latest

### Elixir & Erlang/OTP versions

just docker default

### Operating system

linux

**Comment by sl1depengwyn** [comment] 2024-06-03 11:57
Duplicate of https://github.com/orgs/blockscout/discussions/10181

**Closed by sl1depengwyn** 2024-06-03 11:57 UTC
Labels: triage
